### PR TITLE
breaking(types): Add higher kinded mutator types

### LINKED ISSUE #710: Proposal: Encoding store mutations type-level
Middlewares in zustand can and do mutate the store, which makes it impossible to type them with without some workaround, this proposal tries to encode mutations type-level to make zustand almost 100% type-safe and still extensible.

I'll walk you through how this came to be, because I think it makes one understand how it works and why certain elements of it are necessary.

PR #662 already implements this proposal so you can try it out if you want. And [here](https://tsplay.dev/NlxjeN)'s the final playground to try things out.

## Index

This is less of a "table of content" and more of an "index", meaning the whole thing is single-read and there are no independent "sections" per se, they are made as such to aid the reader to track their progress because this document is rather too long to be a single-read.

- Independent mutations
  - Forwarding mutations up the tree
  - Forwarding mutations down the tree
  - Ordered writes
  - Subtractive mutations
- Dependent mutations
  - Higher kinded mutations
  - Higher kinded mutators
- Zustand-adapted version
- To-dos
  - Caveats
  - Others
- Action point

## Independent mutations

Consider this scenario (I'll be making the api simpler only for the explanation, there are no api changes required)...

```js
const withA = (a, f) => store => {
  store.a = a,
  return f(store);
}

const withB = (b, f) => store => {
  store.b = b,
  return f(store);
}

let storeOut = create(
  withB("b",
    withA("a",
      storeIn =>
        ({ count: 0 })
    )
  )
)
```

Here both `storeOut` and `storeIn` should be of type `Store<unknown> & { a: string } & { b: string }` (we don't care about inferring the state `{ count: number }` for now)

So how would we approach this? First let's take a simpler version

```js
const withA = (a, f) => store => {
  store.a = a,
  return f(store);
}

let storeOut = create(
  withA("a",
    storeIn =>
      ({ count: 0 })
  ),
)
```

One could begin with something like...

```ts
// https://tsplay.dev/w6XJ6m

declare const create:
  <T, M>
    ( initializer:
        & ((store: Store<T>) => T)
        & { __mutation?: M }
    ) =>
    Store<T> & M

type Store<T> =
  { get: () => T
  , set: (t: T) => void
  }
  
declare const withA: 
  <A, T>
    ( a: A
    , initializer:
        (store: Store<T> & { a: A }) => T
    ) =>
      & ((store: Store<T>) => T)
      & { __mutation?: { a: A } }


let storeOut = create(
  withA("a",
    storeIn =>
      ({ count: 0 })
  ),
)
```

And it works. `storeOut` and `storeIn` are `Store<unknown> & { a: string }`. But why does it work? Intuitively you could think that had the store been immutable the middlewares would have returned the mutation isn't it? That's what we're doing here, the middlewares not only return the initializer but also the mutation to the store.

### Forwarding mutations up the tree

Okay now let's see if it works for a more complex example...

```ts
// https://tsplay.dev/mbGe3W

declare const create:
  <T, M>
    ( initializer:
        & ((store: Store<T>) => T)
        & { __mutation?: M }
    ) =>
      Store<T> & M

type Store<T> =
  { get: () => T
  , set: (t: T) => void
  }
  
declare const withA: 
  <A, T>
    ( a: A
    , initializer:
        (store: Store<T> & { a: A }) => T
    ) =>
      & ((store: Store<T>) => T)
      & { __mutation?: { a: A } }

declare const withB: 
  <B, T>
    ( b: B
    , initializer:
        (store: Store<T> & { b: B }) => T
    ) =>
      & ((store: Store<T>) => T)
      & { __mutation?: { b: B } }


let storeOut = create(
  withB("b",
    withA("a",
      storeIn =>
        ({ count: 0 })
    )
  )
)
```

Hmm, it doesn't work. `storeOut` is `Store<unknown> & { b: string }` and `storeIn` is `Store<unknown> & { a: string }`. Why is that? Because were aren't accommodating the fact that the "child" of `withB` ie `withA` itself comes with its mutation so we need to carry forward mutations up the tree. Let's do that[^1]...

```diff
  // https://tsplay.dev/mpvdzw

  declare const withA: 
    < A
    , T
+   , M extends {}
    >
      ( a: A
      , initializer:
          & ((store: Store<T> & { a: A }) => T)
+         & { __mutation?: M }
      ) =>
        & ((store: Store<T>) => T)
        & { __mutation?:
+            & M
             & { a: A }
          }
```

So when the child itself has a mutation `M` (ie when the initializer has `{ mutation?: M }`) we carry it forward as `{ __mutation?: M & { a: A } }` instead of just `{ __mutation?: { a: A } }`.

Also the `extends {}` constraint on `M` is so that it doesn't get fixated to `undefined` because of the `?` in `{ __mutation?: M }`.

### Forwarding mutations down the tree

Okay so now the mutation is forwarded upstream and `storeOut` is `Store<unknown> & { a: string } & { b: string }`. But `storeIn` is still `Store<unknown> & { a: string }`. That's because we have only forwarded mutations upstream, we also need to forward the mutations downstream. Let's see how we can do that...

```diff
  // https://tsplay.dev/m3aLqw

  declare const withA: 
    < A
    , T
    , Mc extends {}
+   , Mp extends {}
    >
      ( a: A
      , initializer:
          & ((store:
              & Store<T>
+             & Mp
              & { a: A }
            ) => T)
          & { __mutation?: Mc }
      ) =>
        & ((store:
            & Store<T>
+           & Mp
          ) => T)
        & { __mutation?: Mc & { a: A } }
```

But it doesn't compile. Why so? Let me first show you a minimal equivalent of the above...

```ts
// https://tsplay.dev/wR9kXW

declare const create:
  <T>(initializer: (store: Store<T>) => T) => Store<T>

type Store<T> =
  { get: () => T
  , set: (t: T) => void
  }
  
declare const identityMiddleware: 
  <T, S extends Store<T>>
    (initializer: (store: S) => T) =>
      (store: S) => T

let storeOut = create(
  identityMiddleware(
    storeIn =>
      ({ count: 0 })
  )
)
```

Now what's happening here? Why does it not compile? The problem is TypeScript can't contextually infer `S`, it eagerly resolves it to `Store<unknown>`. And why does it do that? Well it'll take me rather too long to develop what I know intuitively so [this comment](https://github.com/microsoft/TypeScript/issues/44999#issuecomment-883531098) is the best I can offer right now.

Long story short it doesn't work, we need a workaround. Which looks something like this...

```diff
  // https://tsplay.dev/wX2ALm

  declare const withA: 
    < A
    , T
    , Mc extends {}
    , Mp extends {}
    >
      ( a: A
      , initializer:
          & ( ( store:
                & Store<T>
                & Mp
                & { a: A }
+             , __mutation: UnionToIntersection<Mp | { a: A }>
              ) => T
            )
          & { __mutation?: Mc }
      ) =>
        & ( ( store:
              & Store<T>
-             & Mp
+           , __mutation: Mp
            ) => T
          )
        & { __mutation?: Mc & { a: A } }

+ type UnionToIntersection<U> =
+   (U extends unknown ? (u: U) => void : never) extends (i: infer I) => void
+     ? I
+     : never
```

So instead of passing the mutation from parent as `(store: Store<T> & Pm) =>` we're doing `(store: Store<T>, __mutation: Pm) =>` which in spirit is the same thing. And instead of `Pm & { a: A }` we trick the compiler by doing `UnionToIntersection<Pm | { a: A }>` which is effectively resolves to the same thing.

Why does all this works? Well, I kinda vaguely know it in my "feels" but it's going to take me a lot of experimentation to come up with a good enough theory, so let's just skip that xD

So now finally `storeOut` and `storeIn` both are `Store<unknown> & { a: string } & { b: string }`

### Ordered writes

What if we have a scenario like this...

```js
const withA = (a, f) => store => {
  store.a = a;
  return f(store)
}

let storeOut = create(
  withA(1,
    withA("a",
      storeIn =>
        ({ count: 0 })
    )
  )
)
```

Here with our existing approach `storeOut` and `storeIn` would be `Store<unknown> & { a: number } & { a: string }` when it should have been `Store<unknown> & { a: string }`. That means we need to "write" instead of just intersecting and order of mutations matters too. Let's see how we can do that...

```diff
  // https://tsplay.dev/NnXdvW

  declare const withA: 
    < A
    , T
-   , Mc extends {}
+   , Mcs extends {}[] = []
-   , Mp extends {}
+   , Mps extends {}[] = []
    >
      ( a: A
      , initializer:
-         & ( ( store: Store<T> & Mp & { a: A }
+         & ( ( store: Mutate<Store<T>, [...Mps, { a: A }]>
-             , __mutation: UnionToIntersection<Mp | { a: A }>
+             , __mutations: [...Mp, { a: A }]
              ) => T
            )
-         & { __mutation?: Mp }
+         & { __mutations?: Mps }
      ) =>
        & ( ( store: Store<T>
-           , __mutation: Mp
+           , __mutations: Mps
            ) => T
          )
-       & { __mutation?: { a: A } & Mps  }
+       & { __mutations?: [{ a: A }, ...Mcs] }

+ type Mutate<S, Ms> =
+   Ms extends [] ? S :
+   Ms extends [infer M, ...infer Mr] ? Mutate<Write<S, M>, Mr> :
+   never
+ 
+ type Write<T, U> =
+   Omit<T, keyof U> & U
```

`Mps` happen before because they are come from the parent, `Mcs` happen after because they come from the child.

Note that we are doing `= []` for `Mcs` and `Mps` because previously when there's no `{ __mutation }` found (like in case of `() => ({ count: 0 })`) the compiler would resolve them to their constraints ie `{}` which also happened to be the default. Now the default is `[]` so we need to make it explicit. So technically speaking previously too we should have had `Mc extends {} = {}` but that's almost same as writing `Mc extends {}`.

So now `storeOut` and `storeIn` are `Mutate<Store<unknown>, [{ a: string }, { a: number }]>` except that in case of `storeOut`, `number` gets narrowed to `1`. We can fix that by blocking inference of `A` at the places it isn't supposed to be inferred from...

```diff
  // https://tsplay.dev/Wk5d2N

  declare const withA: 
    < A
    , T
    , Mcs extends {}[] = []
    , Mps extends {}[] = []
    >
      ( a: A
      , initializer:
-         & ( ( store: Mutate<Store<T>, [...Mps, { a: A }]>
+         & ( ( store: Mutate<Store<T>, [...Mps, { a: NoInfer<A> }]>
-             , __mutations: [...Mps, { a: A }]
+             , __mutations: [...Mps, { a: NoInfer<A> }]
              ) => T
            )
          & { __mutations?: Cm }
      ) =>
        & ((store: Store<T>, __mutations: Pm) => T)
-       & { __mutations?: [{ a: A }, ...Mcs] }
+       & { __mutations?: [{ a: NoInfer<A> }, ...Mcs] }

+ type NoInfer<T> =
+   [T][T extends unknown ? 0 : never]
```

So now we're inferring `A` only from the argument, as it should be. And now `number` no longer gets narrowed to `1`.

Also remember that child mutations can also happen before the current one, example...

```js
const withA = (a, f) => store => {
  let state = f(store)
  store.a = a;
  return state;
}

let storeOut = create(
  withA(1,
    withA("a",
      storeIn =>
        ({ count: 0 })
    )
  )
)
```

In this case we'd expect `storeOut.a` to be `number` instead of `string` unlike the previous case. Depending on the implementation, the author can type the middleware accordingly, in this case we're first doing the child mutations so the type becomes...

```diff
  // https://tsplay.dev/wg6kbW

- & { __mutations?: [{ a: NoInfer<A> }, ...Mcs] }
+ & { __mutations?: [...Mcs, { a: NoInfer<A> }] }
```

### Subtractive mutations

Although rare but it's important to note that now mutations can make a store no longer extend `Store<T>`, in that case some cases that should compile won't compile, example...

```js
// https://tsplay.dev/WYBpEw

const withReadonly = f => store => {
  let readonlyStore = { ...store };
  delete readonlyStore.set;
  return f(store);
}

let storeOut = create(
  withReadonly(
    withA("a",
      storeIn =>
        ({ count: 0 })
    )
  )
)
```

If you scroll at the end of the error message you'd see it says "'undefined' is not assignable to type '(t: unknown) => void'" that's because `withA`'s type says it requires `Store<T>` when in fact it doesn't use `set` and only sets a property `a`. Previously, we moved from `(store: Store<T> & Pm) =>` to `(store: Store<T>, __mutation: Pm) => void` because the former didn't work. But now we can go back to that and use `Mutate<Store<T>, Mps>` which would solve our problem and make it compile...

```diff
// https://tsplay.dev/WvYdRm

-       & ((store: Store<T>, __mutations: Mps) => T)
+       & ((store: Mutate<Store<T>, Mps>, __mutations: Mps) => T)
```

But what if `withA` actually requires `set` and want the store to be of type `Store<T>`? In that case we can specify our requirements and then we get the original error back which is now warrant...

```diff
// https://tsplay.dev/WyO7dN

-       & ((store: Mutate<Store<T>, Mps>, __mutations: Mps) => T)
+       & ((store: Mutate<Store<T>, Mps> & Store<T>, __mutations: Mps) => T)
```

It's important to only specify only what we require in the implementation, for example if `withA` only cared about `get` it should specify only that would then make our code compile again as it should...

```diff
// https://tsplay.dev/W4y1ew

-       & ((store: Mutate<Store<T>, Mps> & Store<T>, __mutations: Mps) => T)
+       & ((store: Mutate<Store<T>, Mps> & Pick<Store<T>, "get">, __mutations: Mps) => T)
```

## Dependent mutations

At any point if our mutation has a `T` on a covariant position, it no longer compiles. Basically if the middleware (mutation) "gives" or "returns" the state it means `T` is on a covariant position (like in case of `persist`, `onHydrate` and `onFinishHydration` "give" the state), it won't work. Here's a simple example...

```js
// https://tsplay.dev/mx6dKw

const withSerialized = f => store => {
  store.getSerialized = () => serialize(store.get())
  // Edit: I realized later this is an stupid example
  // but I'm too lazy to edit it. We'll just pretend
  // `serialize` is an identity function.
  // Perhaps a more realistic but yet simple example
  // would be `getNormalised` or something where the
  // it returns `Normalized</* covariant */ T>`.
  // The realest example is ofc `persist` as I
  // mentioned above.

  return f(store)
}

let storeOut = create(
  withSerialized(
    withA("a",
      storeIn =>
        ({ count: 0 })
    )
  )
)
```

If you scroll to the end of the huge error you'd find something like `WithSerialized<unknown> is not assignable to WithSerialized<never>`. The thing for some reason typescript (this could be a bug) resolves `T` to `never` instead of `unknown` assuming it to be contravariant.

I can make it compile [by making all signatures bivariant](https://tsplay.dev/wQen7w) but still `storeIn` would have `WithSerialized<never>` instead of `WithSerialized<unknown>` so that doesn't work. It'd work if `T` is already concrete either [via user explicitly typing it](https://tsplay.dev/WYBxEw) or [via a helper](https://tsplay.dev/N53KZW). These solutions could work but let's actually solve the problem.

### Higher kinded mutations

One thing is clear that we can't have `T` directly on the mutations, that is to say we can't have `{ a: A, t: T }` as a mutation so instead we'll use an emulated higher kinded type `(T, A) => { a: A, t: T }` and inject `T` (and an optional payload like `A` in this case)...

```diff
  // https://tsplay.dev/N9poJw

+ interface StoreMutations<T, A> {}
+ type StoreMutationIdentifier = keyof StoreMutations<unknown, unknown>

  declare const withSerialized:
    < T
-   , Mcs extends {}[] = []
+   , Mcs extends [StoreMutationIdentifier, unknown][] = []
-   , Mps extends {}[] = []
+   , Mps extends [StoreMutationIdentifier, unknown][] = []
    >
      ( initializer:
-         & ( ( store: Mutate<Store<T>, [...Mps, WithSerialized<T>]>
+         & ( ( store: Mutate<Store<T>, [...Mps, ["WithSerialized", never]]>
-             , __mutations: [...Mps, WithSerialized<T>]
+             , __mutations: [...Mps, ["WithSerialized", never]]
              ) => T
            )
          & { __mutations?: Mcs }
      ) =>
        & ((store: Mutate<Store<T>, Mps> __mutations: Mps) => T)
-       & { __mutations?: [WithSerialized<T>, ...Mcs] }
+       & { __mutations?: [["WithSerialized", never], ...Mcs] }
  
+ interface StoreMutations<T, A>
+   { WithSerialized: { getSerialized: () => T }
+   }
  
  declare const withA: 
    < A
    , T
-   , Mcs extends {}[] = []
+   , Mcs extends [StoreMutationIdentifier, unknown][] = []
-   , Mps extends {}[] = []
+   , Mps extends [StoreMutationIdentifier, unknown][] = []
    >
      ( a: A
      , initializer:
-         & ( ( store: Mutate<Store<T>, [...Mps, { a: NoInfer<A> }]>
+         & ( ( store: Mutate<Store<T>, [...Mps, ["WithA", NoInfer<A>]]>
-             , __mutations: [...Mps, { a: NoInfer<A> }]
+             , __mutations: [...Mps, ["WithA", NoInfer<A>]]
              ) => T
            )
          & { __mutations?: Mcs }
      ) =>
        & ((store: Mutate<Store<T>, Mps>, __mutations: Mps) => T)
-       & { __mutations?: [{ a: NoInfer<A> }, ...Mcs] }
+       & { __mutations?: [["WithA", NoInfer<A>], ...Mcs] }
      
+ interface StoreMutations<T, A>
+   { WithA: { a: A }
+   }
  
- type Mutate<S, Ms> =
+ type Mutate<S, Ms, T = S extends { get: () => infer T } ? T : never> =
    Ms extends [] ? S :
-   Ms extends [infer M, ...infer Mr]
+   Ms extends [[infer I, infer A], ...infer Mr]   
      ? Mutate<
          Overwrite<
            S,
-           M
+           StoreMutations<T, A>[I & StoreMutationIdentifier]
          >,
          Mr
        > :
    never
```

So instead of passing around mutations `M` we pass "functions" `(T, A) => M` that take `T` and some optional payload. So writing...

```ts
type M<A> = ["WithFoo", A]

interface StoreMutations<T, A>
  { WithFoo: { t: T, a: A }
  }
```

...is in spirit same as writing a higher kinded type...

```ts
type M<A> = T -> { t: T, a: A }
```

So `StoreMutations` is a collection of "mutation creators". And now as you can see in the diff `M` becomes `StoreMutations<T, A>[I & StoreMutationIdentifier]`[^2]. Writing `StoreMutations<T, A>[I]` is in spirit writing `storeMutations[i](t, a)` which would return `m`.

`StoreMutations` is also a "global" collection so it can be augmented anywhere and new mutations can be added. It works across files thanks to module augmentation and declaration merging, so in reality adding a mutation would look like this...

```ts
// @file node_modules/zustand/index.ts
export interface StoreMutations<T, A> {}

// @file node_modules/zustand-with-serialized/index.ts
declare module "zustand" {
  interface StoreMutations<T, A>
    { WithSerialized: { getSerialized: () => T }
    }
}
```

### Higher kinded mutators

Now that we are using higher kinded types, we can simplify things a bit and instead of `newStore = overwrite(oldStore, storeMutations[mi](tFromOldStore, a))` just simply do `newStore = storeMutators[mi](oldStore, a)`.

```diff
  // https://tsplay.dev/NrGk2m

- interface StoreMutations<T, A>
-   { WithSerialized: { getSerialized: () => T }
-   }

+ interface StoreMutators<S, A>
+   { WithSerialized:
+       S extends { get: () => infer T }
+         ? Write<S, { getSerialized: () => T }>
+         : never
+   }

- interface StoreMutations<T, A>
-   { WithA: { a: A }
-   }

+ interface StoreMutators<S, A>
+   { WithA: Write<S, { a: A }>
+   }
  
- type Mutate<S, Ms, T = S extends { get: () => infer T } ? T : never> =
+ type Mutate<S, Ms> =
    Ms extends [] ? S :
    Ms extends [[infer Mi, infer A], ...infer Mr]   
      ? Mutate<
-         Write<
-           S,
-           StoreMutations<T, A>[Mi & StoreMutationIdentifier]
-         >,
+         StoreMutators<S, A>[Mi & StoreMutatorIdentifier],
          Mr
        > :
    never
```

## Zustand-adapted version

[Here](https://tsplay.dev/mMVDVW)'s a version that is compatible with zustand's api (same as in #662), uses unique symbols for identifiers, a reusable `StoreInitializer`, etc and an example middleware.

## To-dos

This is still sort of incomplete here are some things left to figure out...

### Caveats

It doesn't compile if you don't write all middlewares in place because it relies on contextual inference, meaning this doesn't compile...

```js
// https://tsplay.dev/w6X96m

let foo = withB("b", () => ({ count: 0 }))
let store = create(withA("a", foo))
```

... but this does ...

```js
// https://tsplay.dev/WPxDZW

let store = create(withA("a", withB("b", () => ({ count: 0 }))))
```

I recently noticed this caveat so I haven't really worked on it. Maybe I could make it at least compile will a little less accuracy in types.

### Other

- Migration plan? What changes do users need to make?
- `createWithState`? Probably a good idea.
- If we'll be having `createWithState` do we still need higher kinded types? Maybe, maybe not.
- Is this pipeable? Can we make a custom pipe that works?
- ...

## Action point

I'd like to know if this seems like a good idea or not, if yes then I'll continue with the to-dos. If no then how far should we go wrt to types?

Thanks for reading all this! Hopefully I've not made much mistakes. Feel free to ask questions

[^1]: Note that the diffs through out the document are just gists, they are not exact it excludes some obvious changes elsewhere (like in `create`) and also renames variables, changes formatting etc. The diff is minimal enough to get the crux of what changed. Go to the playground link to see the full change

[^2]: The `& StoreMutationIdentifier` is to just satisfy the compiler that `I` indeed is a key of `StoreMutations` (as `X & Y` will always be a subtype of `Y`). `I & StoreMutationIdentifier` is same as `I` because `I` already is a subtype of `StoreMutationIdentifier`, eg `"WithSerialized" & ("WithSerialized" | "WithA")` is `"WithSerialized"`.

### LINKED ISSUE #882: Using a persisted store with createContext and TypeScript
Hi all,

We're using the store persistence in conjunction with a context to provide the store to all parts of the application. Since the persist callback modifies the returned useStore hook we are having trouble getting TypeScript to recognize the persist property of the hook.

We tried modifying the create type itself to match the middleware tests as indicated in the code comment(https://github.com/pmndrs/zustand/blob/main/src/middleware/persist.ts#L91):

```
const useStore = create<
        IStore,
        SetState<IStore>,
        GetState<IStore>,
        Mutate<StoreApi<IStore>, [['zustand/persist', Partial<IStore>]]>
    >(
```

However this didn't solve our root issue because we are accessing useStore from a context. Looking at the createContext function I'm not sure how to pass in the correct types so useStore has the persist property. How do you intend to use both persist and createContext with TypeScript? https://github.com/pmndrs/zustand/blob/main/src/context.ts#L15
https://github.com/pmndrs/zustand/blob/main/src/context.ts#L60

I can provide a PR with proposed changes if that is preferred.

### LINKED ISSUE #909: Proposal: Use NamedSet everywhere
`NamedSet` is a variation of `SetState` that accepts a third argument for passing in a string, for naming actions. This is used by the devtools middleware to have named logs.

Unfortunately having these two different types for `SetState` can cause all sorts of problems when chaining middlewares, where that third argument gets lost in the mix, etc.

What's the reason for not just using `NamedSet` by default? Why can't that optional argument always be there and we can get rid of an entire type? It doesn't always have to be consumed by other middlewares but it should always be passed on

### PR DESCRIPTION
**Pull request by devanshj**
Okay @dai-shi now you have two options:

**A. This PR (not complete yet)**
Makes the change as minimal as possible, just adds the types proposed in #710, zero change in runtime code.

**B. #662**
Not only adds #710 but also rewrites the whole codebase to drastically increase the code quality. Don't mind me but the current code is quite a mess, I like to write code for fun so I thought let's rewrite this whole thing nicely. Now this obviously will produce relatively large and unhelpful diffs, nothing can be done about that. It would be much easier to review if you compare the files locally without the red-green diff.
But now I have a small condition: I'll remove prettier and some lint rules, but don't worry you can add them back but you'll have to do it yourself (you have the edit rights). Consider this a little treat that I'm giving myself :P I hope you won't mind.

Let me know which of the two options you prefer. If you think increasing the code quality is worth taking the pain to review, I'd suggest you go with the second option. I don't mind whichever you pick.

### CODE REVIEW

**Comment by dai-shi** [comment]
@devanshj I really appreciate your work on these.
tbh, I like this PR approach. at the same time, I like your rewrite too.

Sorry, I mixed two concerns in my previous comments in other PRs.
The first concern is backward compatibility for users.
The second concern is my ability to review the entire (rewritten) code at once.

So, to summarize my thoughts again:
- We want to keep 100% backward compatible for JS code in v4.0.0
- We want to fix store types with mutator types in v4.0.0 (reverting my work in v3.6.x is rather welcome. type breaking change for this fix is acceptable.)
- Let's keep exported type names backward compatible even if they are little weird. (We don't just rename types for better ones if the types are the same.)
- I actually want (and had even wanted in v3) to drop some exported types in v4.0.0 (deprecate them in v3.7.0) if they don't confuse people too much.
- I want to release v4.0.0 with minimal diff, and rewrite the whole code base step by step without changing exported types after releasing. So, we need to foresee what types to drop in advance for the rewrite.

Again, I prefer this PR approach, but want to take the rewrite idea as much as possible.
Probably, your full rewrite in #662 isn't possible with this approach, but we could try best effort.

**Comment by devanshj** [comment]
Got it, so let's go with this PR. Then once this is ready we'll release it in v4.0.0 and we can do a rewrite later if wanted.

Regarding dropping some types, `vanilla.ts` is ready on this PR, you can comment which ones you're thinking of dropping for v4. My suggestions are in #715 for reference.

File: src/vanilla.ts [hunk 1]
```diff
@@ -104,50 +80,34 @@ function createStore<
...
+
+export default create
+
+type CreateWithState = <T extends State>() => <
+  Mos extends [StoreMutatorIdentifier, unknown][] = []
+>(
+  initializer: StateCreator<T, [], Mos>
+) => Mutate<StoreApi<T>, Mos>
+
+export const createWithState: CreateWithState = () => create
```
Comment (dai-shi) [inline src/vanilla.ts:113]: This looks like the trick of the whole thing. Is this internal use only? We don't want to expose this to library users.

File: src/vanilla.ts [hunk 2]
```diff
@@ -45,44 +23,42 @@ export type StoreApi<T extends State> = {
...
-  CustomGetState,
-  CustomStoreApi extends StoreApi<TState>
+  Mis extends [StoreMutatorIdentifier, unknown][],
+  Mos extends [StoreMutatorIdentifier, unknown][],
+  U = T
+> = ((
+  setState: Get<Mutate<StoreApi<T>, Mis>, 'setState', undefined>,
+  getState: Get<Mutate<StoreApi<T>, Mis>, 'getState', undefined>,
+  store: Mutate<StoreApi<T>, Mis>,
+  $$storeMutations: Mis
```
[the remark this answers is not in the document]
Comment (dai-shi) [reply src/vanilla.ts:38]: Is this only for the internal use?

**Review by dai-shi — COMMENTED** [review]
Reviewed vanilla.ts. This is still tough, but at least far more readable than #662 for me.
I wonder if we still have design options, like giving up something.

File: src/vanilla.ts [hunk 3]
```diff
@@ -1,42 +1,20 @@
...
-    K2 extends keyof T = K1,
-    K3 extends keyof T = K2,
-    K4 extends keyof T = K3
-  >(
-    partial: PartialState<T, K1, K2, K3, K4>,
-    replace?: boolean
-  ): void
-}
+export type SetState<T extends State> = <
+  Nt extends R extends true ? T : Partial<T>,
```
[the remark this answers is not in the document]
Comment (devanshj) [reply src/vanilla.ts:12]: "New State" as `state` is `T`

File: src/vanilla.ts [hunk 4]
```diff
@@ -45,44 +23,42 @@ export type StoreApi<T extends State> = {
   subscribe: Subscribe<T>
   destroy: Destroy
 }
+
+export const $$storeMutators = Symbol('$$storeMutators')
```
[the remark this answers is not in the document]
Comment (devanshj) [reply src/vanilla.ts:27]: Nope not internal, this is required if you want to author a middleware. I'll later add a "How to write a middleware" section.

File: src/vanilla.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (devanshj) [reply src/vanilla.ts:38]: > This looks unfortunate, but can't be helped, right?

Haha nope.

> Is this only for the internal use?

Yep no one will have to write this, they can just use `StateCreator`.

File: src/vanilla.ts (hunk 1 above)
Comment (devanshj) [reply src/vanilla.ts:113]: This is what would be the recommended way to create a store for typescript users. See [this comment](https://github.com/pmndrs/zustand/pull/662#discussion_r774789318).

File: src/vanilla.ts [hunk 5]
```diff
@@ -45,44 +23,42 @@ export type StoreApi<T extends State> = {
...
+
+// eslint-disable-next-line @typescript-eslint/no-unused-vars
+export interface StoreMutators<S, A> {}
+export type StoreMutatorIdentifier = keyof StoreMutators<unknown, unknown>
+
+export type Mutate<S, Ms> = Ms extends []
+  ? S
+  : Ms extends [[infer Mi, infer Ma], ...infer Mrs]
+  ? Mutate<StoreMutators<S, Ma>[Mi & StoreMutatorIdentifier], Mrs>
+  : never
```
[the remark this answers is not in the document]
Comment (devanshj) [reply src/vanilla.ts:49]: This 99% won't break, if it does I'm there to help. But yeah this is unfamiliar to most people.

File: src/vanilla.ts [hunk 6]
```diff
@@ -45,44 +23,42 @@ export type StoreApi<T extends State> = {
...
-    TState,
-    CustomSetState,
-    CustomGetState,
-    CustomStoreApi
-  >
-): CustomStoreApi {
+  initializer: StateCreator<T, [], Mos>
+) => Mutate<StoreApi<T>, Mos>
+
+const create: Create = (createState) => {
```
[the remark this answers is not in the document]
Comment (devanshj) [reply src/vanilla.ts:60]: We can but then what would you call `createWithState`? `createStoreWithState`? That becomes too long.

**Comment by devanshj** [comment]
> I wonder if we still have design options, like giving up something.

Even if we give up some things the types still will be complex. And more over the users don't have to face any of the current complexity.

Regarding the `createWithState` thing, the users will be happy because now they don't have to annotated the store type. Take a look at diff of `middlewareTypes.test.tsx` in #662. Here's an [example](https://github.com/pmndrs/zustand/pull/662/files#diff-c65003d390ca71427c9de9367e1d32d897005c245143ad673cad2c73d79005ecL385-L390):

```diff
-     const useStore = create<
-       CounterState,
-       SetState<CounterState>,
-       GetState<CounterState>,
-       StoreApiWithPersist<CounterState> & StoreApiWithDevtools<CounterState>
-     >(
+     const useStore = createWithState<CounterState>()(
```

File: src/vanilla.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (dai-shi) [reply src/vanilla.ts:12]: Ah,,, fine. I'll propose something if I have any.

File: src/vanilla.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (dai-shi) [reply src/vanilla.ts:27]: Okay, for middleware authors.
Module variables are really hard to deal with for bundling. (zustand doesn't depend on it now.)
Can this be a string? Otherwise, I might consider using `Symbol.for()`.

File: src/vanilla.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (dai-shi) [reply src/vanilla.ts:38]: Just wondering if there can be two types: one for normal lib users, and the other for middleware authors.

File: src/vanilla.ts (hunk 1 above)
Comment (dai-shi) [reply src/vanilla.ts:113]: Why can't this be the default, then?
This is very important for zustand. Zustand really prefers to export one function.
It's unacceptable to export two functions from vanilla.ts.

File: src/vanilla.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (devanshj) [reply src/vanilla.ts:27]: Yep it can be a string. Would you want to make the middleware symbols (like `$$persist`) strings too? That also can be done. (we don't have to worry about uniqueness as `StoreMutators` requires all keys to be unique)

**Comment by dai-shi** [comment]
Yeah, that was ugly. That was not my original expectation when I started.
But, you can't assume all TS users skill level and you alone can't teach them all.
Like, some people prefer annotating types rather than inferring types.

File: src/vanilla.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (devanshj) [reply src/vanilla.ts:38]: > Just wondering if there can be two types: one for normal lib users, and the other for middleware authors.

But normal lib users will have to not write any types :) the only type they have to write is the type of their state.

**Comment by devanshj** [comment]
> But, you can't assume all TS users skill level and you alone can't teach them all.

I know what you're saying but if they can read the release and migration notes they'll be able to pick it up

> Like, some people prefer annotating types rather than inferring types.

I doubt in this case anyone would want to annotate the store types, but in case they want to, they can `create<T, [[$$persist, U], [$$devtools, never]]>()` a little more unfamiliar but arguably better than before.

File: src/vanilla.ts [hunk 7]
```diff
@@ -45,44 +23,42 @@ export type StoreApi<T extends State> = {
...
+> = ((
+  setState: Get<Mutate<StoreApi<T>, Mis>, 'setState', undefined>,
+  getState: Get<Mutate<StoreApi<T>, Mis>, 'getState', undefined>,
+  store: Mutate<StoreApi<T>, Mis>,
+  $$storeMutations: Mis
+) => U) & { [$$storeMutators]?: Mos }
+
+// eslint-disable-next-line @typescript-eslint/no-unused-vars
+export interface StoreMutators<S, A> {}
+export type StoreMutatorIdentifier = keyof StoreMutators<unknown, unknown>
```
[the remark this answers is not in the document]
Comment (devanshj) [reply src/vanilla.ts:43]: > I think only immer breaks store type, other middleware only extends store type, no?

Yep but there are problems even if you only use other middlewares like `devtools` and `persist` as I demonstrated [here](https://github.com/pmndrs/zustand/issues/710#issuecomment-991896767).

File: src/vanilla.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (dai-shi) [reply src/vanilla.ts:27]: okay, let's not use symbols.
i even think we don't need to export the strings, to make sure that it doesn't depend on module variables, at least for some time.

File: src/vanilla.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (dai-shi) [reply src/vanilla.ts:38]: hm, i think this is fine. it's rather internal, and as i understand, it's necessary to propagate types from top to down.

File: src/vanilla.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (dai-shi) [reply src/vanilla.ts:43]: back to the code. these two lines are hard to understand.
how does it work?
https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMpgPZQgWQK5hyZQDOAPKgDTICCAfMgN4C+AUGAJ4AOK6WuBIlgCSAEwjhgMYNGQBeZAGsIHDDDTEBhYuTwhFIDAHcQ1PQeMg6QA
I thought I understood whey I first saw, but now I'm not sure.

File: src/vanilla.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (dai-shi) [reply src/vanilla.ts:49]: why do we need `StoreMutators` and `StoreMutatorIdentifier` for `Mutate`? Are they only to guarantee the uniqueness?

File: src/vanilla.ts (hunk 1 above)
Comment (dai-shi) [reply src/vanilla.ts:113]: I think you have already considered, but can't we overload functions?

**Comment by devanshj** [comment]
> oops, did i stop you moving forward?

No no haha, I was taking a little break to work on [`@sthir/predicate`](https://github.com/devanshj/sthir/tree/main/packages/predicate), which is quite complete now.

I'll get back to this soon, hopefully in a day or two!

**Comment by devanshj** [comment]
> back to the code. these two lines are hard to understand.
how does it work?
https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMpgPZQgWQK5hyZQDOAPKgDTICCAfMgN4C+AUGAJ4AOK6WuBIlgCSAEwjhgMYNGQBeZAGsIHDDDTEBhYuTwhFIDAHcQ1PQeMg6QA
I thought I understood whey I first saw, but now I'm not sure.

> why do we need `StoreMutators` and `StoreMutatorIdentifier` for Mutate? Are they only to guarantee the uniqueness?

The idea is we want a way to "pass" types from one module to another module. So to do that what we do is we declare an interface in the module the needs to receive the type and in the modules that needs to send the type we augment the interface, here's an example...



So you can think of all export interfaces as "global" any other module can append new properties to them.

Now we need a global "registry" of middleware mutators, hence we define an interface `StoreMutators` which all middleware modules would add append their mutators and then we'd use those mutators in `Mutate`. So when we write...

```
// @file devtool.ts
interface StoreMutators<S, A>
  { [$$devtools]: WithDevtools<S, A>
  }
```

...we're actually passing the `WithDevtools` type to `vanilla.ts` which will use it in `Mutate`

Also we don't really need to worry about uniqueness because if you different modules append two different mutators then typescript would so them error.



But the thing is the user is importing a third party module then if there are name clashes then it becomes a problem because the third party person won't know what names are already registed, so we'll keep a convention to for third party middleware authors to start the mutator name with their npm package name (the exported function name can be anything ofc). So for zustand, it'd become `"zustand/devtools": WithDevtools<S, A>` etc.

My suggestion would be to use symbols for this purpose, but I'm with this convention too.

And lastly we use `StoreMutatorIdentifier` simply has a short hand for writing `keyof StoreMutators<unknown, unknown>` to get a type of all mutators that are registered.

File: src/vanilla.ts (hunk 1 above)
Comment (devanshj) [reply src/vanilla.ts:113]: I actually didn't think of overloads, that's a good idea, I'll update to use overloads.

Comment (dai-shi) [reply src/vanilla.ts:113]: This is a major blocker. I hope it will work well!

**Comment by dai-shi** [comment]
> The idea is we want a way to "pass" types from one module to another module. So to do that what we do is we declare an interface in the module the needs to receive the type and in the modules that needs to send the type we augment the interface, here's an example...

Thanks for the explanation. I think I understand the concept. And, I feel like I should understand it better.
May I ask you a favor? Would you create a small standalone typescript playground with this idea, so that I can play with it?

**Comment by devanshj** [comment]
> Would you create a small standalone typescript playground with this idea, so that I can play with it?

Sure, does [this](https://tsplay.dev/mx6A7w) work? Or you need something even more minimal? [Here](https://tsplay.dev/wQe9nw)'s a more minimal version of that only shows how `Mutate` works.

**Comment by devanshj** [comment]
> [Here](https://tsplay.dev/N53XoW)'s a more minimal version of that only shows how `Mutate` works.

I think you already understand how it work but here's a JS version of the above type-level code...

```js
const storeMutators = {}
// interface StoreMutators<S, A> {}

storeMutators.withA = (s, a) => Object.assign({}, s, { a: a })
// interface StoreMutators<S, A>
//  { withA: Write<S, { a: A }>
//  }
  
storeMutators.withB = (s, a) => Object.assign({}, s, { b: a })
// interface StoreMutators<S, A>
//  { withB: Write<S, { b: A }>
//  }

const mutate = (s, ms) =>
  ms.length === 0 ? s :
  (([[mi, ma], ...mrs]) => mutate(storeMutators[mi](s, ma), mrs))(ms)
  
// type Mutate<S, Ms> =
//   Ms extends [] ? S :
//   Ms extends [[infer Mi, infer Ma], ...infer Mrs]
//     ? Mutate<
//        StoreMutators<S, Ma>[Mi & StoreMutatorIdentifier],
//        Mrs
//      > :
//  never

const testStore = mutate({ get: () => {} }, [["withA", "hello"], ["withB", "world"]]); 
// type TestStore = Mutate<Store<{ count: number }>, [["withA", string], ["withB", string]]>

console.log(testStore)
```
<details>
<summary>Console Output: </summary>

console output
</details>

**Comment by devanshj** [comment]
This is almost ready now

**Comment by dai-shi** [comment]
> [Here](https://tsplay.dev/N53XoW)'s a more minimal version of that only shows how `Mutate` works.

This really helps.
I just missed the fact `interface` can be overloaded. 😓 

[This](https://www.typescriptlang.org/play?pretty=false#code/C4TwDgpgBAKhDOwDKwD2AnaBeKBZArsAIbAQA8KG5A3lAMar4B2wAXFE-gLYBGE6UAL4A+ADRQA2hIBEAdwCWwABYBBaeMTp5TAOYBdcTIXKAQuqibt+vcIDcAKAD0jqK6gA9APz3720ugAzIjpoSkwCYjR0eApxFWEoantXY1V2AHUtUljEqCJ2FSE7e0EfP34gkKgwiAiSDBikOISklMUlEwys8ibcngKih1L7UEhqqPIYBJxWi0iIdhghh18WCuDQibqoxubE0tHNqm2MAEkAEwgWeQD5figcAGsIEFQA8ePCeuiyZkemVCyJjiP4AoHFEbgaDbHriXDwaZ4eBQCAAD1ITHOyIkemSUE81Tx7HhKPRVyxkgk2gC91w8nE1NpRAMUAAdOzGQJcNFca4CXTSRiKTUTugLldgDc7ug8Xy8F9siKFQ0crgiMIJHSWdyEbKoOwmBAAG78IkcY38FaHKCZRSTcQAVURAHkuIoyDBxM9Xu8nVAAGRQB0OIA) is what I tried. I understand 100% of this.

Now, it made me think [this](https://www.typescriptlang.org/play?pretty=false#code/C4TwDgpgBAKhDOwDKwD2AnaBeKBZArsAIbAQA8KG5A3lAMar4B2wAXFE-gLYBGE6UAL4A+ADRQA2rSLtE6AJZMA5kPG0e7Tr35CAusIDcAKAD0JqBagA9APxGjoSFEqYyMYVBzUjFxCQjsMMaCxg7g0ATEpBTiuPAeOHFQEAAepEwAJvCSuj5QNs557Emp6VmSigBmOrjiAHQNVTXo8LmW+XiE-mQA6grRSLFieC3CRRwQAG78oY7QffLRMOIAqglQAPJci27iANYQIKiVUGtQAGSnxkA) works. But, it doesn't work in practice in our case???

---
btw, I'm so amazed to see `^?` in the playground. Where can I find such tips in docs?
Also, how do you create the tsplay.dev shorten url?

**Comment by dai-shi** [comment]
> Sure, does [this](https://tsplay.dev/mx6A7w) work?

So, [this](https://www.typescriptlang.org/play?#code/DYUwLgBAzmD2BOIDyBXSBeCBjRBDMIAPAN7awoB2YAXBBSgLYBGI8EAvgHwAUAlNwCgIEAO4BLMAAsAgoOHCARLgUAaIfPFSAQtwVNVEbjAQgAkhV4R0nQ6SzkqtAAwdevde94BuAQLFVWADNcLBAIAGU4REIAFQgQAA8CCgATKAgAVQoAawpYEQpI-BAbYnUAc3Aiglo+KxsYn2EoKrBi2kIAOUhE5LSIACV4pJBU9LB4FDCAfgg42gAFXHgwMVxgWM4VQeG+9KZYWFBcCh51YQpe6uR4DIAHFOL4Wm6IAB9DIzaauctrCG6vDU8mgknIwBSAxAd2AIRA01oAw89QgADdYGIUk1oCgmFAcGIWLVgGIYKNWLUYO05ts7ohUWJyFBrrQYn8bOjMezDNzOVj1CkQDB4LAAJ61XkY-nsXxgUV3MJZXL5QrfMKYWBMABWICwYB8AkFWFhiDIFBg2DwPzKwliu1G-SVeQK122AFlYOleg70pRlQUANoAXSsEGDZxB-gkaxJAC8KREomYKNH1mJ4-BYttg+7PZwPLQ3WhioRIiZNrmoJxsXbvWNMjlnarijxeB0PV6RvW-U3g6Hw3J5FHVmmM7Qy4hzKm46ws2Gg5X88JuUW1aWkxWIB3qwJ2Aa5QrEyYpyOZ5m4nXHY2Va6t6TK9sMqGYjZMNxB8ZEIXiwR1+WX+6pJbOoAAkIGfiAq74Iy5qFqSAjchklgAGQQDaEBgRBUGrLA5oIluno+HusrymE2FEOE7pVqGbqdns87qLM4TqIWdE+mG-iBKwW7bAAdPxnHcW68BQEGjFbj+RAAOrwBIFHulsW4iUuEC0JcqKsAaRommE9jmpAmgyB06gXl2V7+s2BDAhA0jWW6dxsd216BiGmA5uobpYI5-Q9iqfZuWJEYQLgtC2eow4xumCYTsm05Ree2b8bx9lQNspAhQCsDmFxmbSDY7ALluXn5tyMUnpFGZzil2bpS8WUUDlhB5RwfH8Z5ok7n4ATwMEoRHog2EIFApbbM16GGdItAyXJI1ocFoUcDuMqGrqOlmhahlaMZwimfRTo3mq1laHZDn2k5Fn+fOdleWdPnORQl3BgIQVMLQx3hSmp7xeOSblaOs4xIlbUOWlECvZl2Wzlo+WFe1JUomVn0VQD7og2GpDg509WNdDLUQEl7VBp1-gED1cL9ZBP5DbNY3qJtU2yb+lFzeD0iLURJGHgA4uAc4ANLbAAYqG6msK+EB87d6TZCAoqwIEcwQLMMQBnzIa0IL+6kRA02-oDmTi0gDASHOMtywrGQ2KhGRa4eWOQ+e4sBjEQbO1LEC+QUSsQC4akgBp8BBj4QA) is what I modified. Please let me know what would be the pitfall.

**Comment by devanshj** [comment]
> Now, it made me think this works. But, it doesn't work in practice in our case???

> So, this is what I modified. Please let me know what would be the pitfall.


It's good to see you could come up with the simplified version. But it won't work as soon as you have a `T` anywhere (at a covariant) in the mutation. A real example of that is persist: https://tsplay.dev/NaYzyN Note that it would work if you make `T` concrete by passing it as type-parameter: https://tsplay.dev/WzLjRN But that still is not a good solution as the code should at least compile without having to pass type parameters.

Your suggestion is same as the "Ordered writes" section in #710. I suggest you to read from "Dependent Mutations" section onwards because this the place where I begin to explain how I solve this problem and how we end up with `StoreMutators`...

> ## Dependent mutations
>
> At any point if our mutation has a `T` on a covariant position, it no longer compiles. Basically if the middleware (mutation) "gives" or "returns" the state it means `T` is on a covariant position (like in case of `persist`, `onHydrate` and `onFinishHydration` "give" the state), it won't work. Here's a simple example...

---

> btw, I'm so amazed to see ^? in the playground.

Haha yeah it's cool, I think it'll eventually come to vscode too.

> Where can I find such tips in docs?

The docs probably don't mention it, I learnt when someone on the typescript team used it in an issue. [Orta](https://twitter.com/orta) usually implements features of the playground (like this one) so I guess one way to learn more tips is to follow him or twitter.

> Also, how do you create the tsplay.dev shorten url?

One way to do it is first copy the long usual url, then go to tsplay.dev, paste it there and you'd get a shorter version.
Another way to install the plugin in the playground, go to the "Plugins" tab, there should be a "Link Shortener" plugin, tick the checkbox next to it to install it. Then you should be able to use it directly from the playground:

image

**Comment by dai-shi** [comment]
> Your suggestion is same as the "Ordered writes" section in #710. I suggest you to read from "Dependent Mutations" section onwards

Glad to see I'm following your path.

> The thing for some reason typescript (this could be a bug)

So, is this true that, if TS fixes this bug or behavior, we could have a simplified version.

Now, I understand why "Higher kinded mutations" is introduced. Let me see if I can read the code...

> there should be a "Link Shortener" plugin

Ah, I somehow missed it when I looked for it in the plugin list. 😓

File: src/vanilla.ts [hunk 8]
```diff
@@ -45,44 +25,50 @@ export type StoreApi<T extends State> = {
...
-    TState,
-    CustomSetState,
-    CustomGetState,
-    CustomStoreApi
-  >
-): CustomStoreApi {
+  initializer: StateCreator<T, [], Mos>
+) => Mutate<StoreApi<T>, Mos>
+
+const _createStore: CreateStoreImpl = (createState) => {
```
Comment (dai-shi) [inline src/vanilla.ts:70]:
```suggestion
const createStoreImpl: CreateStoreImpl = (createState) => {
```

I prefer this naming. (In TS, `_foo` is used for "unused", so prefer avoiding "internal" meaning.)

File: src/vanilla.ts [hunk 9]
```diff
@@ -104,50 +90,31 @@ function createStore<
 
   const getState: GetState<TState> = () => state
 
-  const subscribeWithSelector = <StateSlice>(
```
Comment (dai-shi) [inline src/vanilla.ts:107]: Could you please make a diff from `v4`? This should already be removed.

File: src/vanilla.ts [hunk 10]
```diff
@@ -104,50 +90,31 @@ function createStore<
...
 }
 
+type PopArgument<T extends (...a: never[]) => unknown> = T extends (
+  ...a: [...infer A, infer _]
+) => infer R
+  ? (...a: A) => R
+  : never
+
+const createStore = ((f) => {
+  if (f === undefined) return _createStore
```
Comment (dai-shi) [inline src/vanilla.ts:116]: Cool.

File: src/vanilla.ts [hunk 11]
```diff
@@ -45,44 +25,50 @@ export type StoreApi<T extends State> = {
...
-  createState: StateCreator<TState, SetState<TState>, GetState<TState>, any>
-): StoreApi<TState>
-
-function createStore<
-  TState extends State,
-  CustomSetState,
-  CustomGetState,
-  CustomStoreApi extends StoreApi<TState>
+  Mis extends [StoreMutatorIdentifier, unknown][],
+  Mos extends [StoreMutatorIdentifier, unknown][],
```
Comment (dai-shi) [inline src/vanilla.ts:32]: Can these have defaults to avoid breaking change?
If it's not possible, we need to make sure to warn it in the release note.

```suggestion
  Mis extends [StoreMutatorIdentifier, unknown][] = [],
  Mos extends [StoreMutatorIdentifier, unknown][] = [],
```

**Review by dai-shi — COMMENTED** [review]
Reviewed `vanilla.ts` only. I'm mostly happy with it. Please check the comments.

**Comment by devanshj** [comment]
> So, is this true that, if TS fixes this bug or behavior, we could have a simplified version.

Yes, although it's very unlikely it'd be a bug.

> Now, I understand why "Higher kinded mutations" is introduced. Let me see if I can read the code...

Yep, the idea is to make `T` somehow disappear from the mutation. So instead of a mutation `{ a: A, t: T }` we use a higher kinded mutation `(T, A) => { a: A, t: T }` and then eventually use a higher kinded mutator `(S, A) => S extends { getState: () => infer T } ? Write<S, { a: A, t: T }> : never` to simplify the things a bit.

File: src/vanilla.ts (hunk 8 above)
Comment (devanshj) [reply src/vanilla.ts:70]: Yeah I think I prefer that too because `fooImpl` is also how other middlewares are implemented

File: src/vanilla.ts (hunk 11 above)
Comment (devanshj) [reply src/vanilla.ts:32]: Hmm, I try to avoid defaults but I think we can have them here for backward compatibility. Although some places where `StateCreator` is used, for eg middlewares, there will be migration needed.

**Comment by dai-shi** [comment]
btw, if I were to design the zustand api from scratch, I'd never introduce type complexity. 😄

**Comment by devanshj** [comment]
> btw, if I were to design the zustand api from scratch, I'd never introduce type complexity. 😄

Haha yeah I'm aware you had mentioned that you too don't like the mutating api

File: src/vanilla.ts (hunk 11 above)
Comment (dai-shi) [reply src/vanilla.ts:32]: I don't like defaults either, if possible.
What about we define two types?
```ts
export type StateCreator<
  T extends State,
> = ...
export type StateCreatorWithMutator<
  T extends State,
  Mis extends [StoreMutatorIdentifier, unknown][],
  Mos extends [StoreMutatorIdentifier, unknown][],
  U = T
> = ...
```

Comment (devanshj) [reply src/vanilla.ts:32]: No I think two types are much worse than defaults because then we'd have to educate users when to use which. Moreover we'll have two types that mostly do the same thing. I'd prefer defaults here.

> Maybe the same thing?

I don't follow what you mean by that haha.

If you're saying that if migration is needed even with defaults then the defaults are not worth much? Well yeah kinda. Do you have cases where users would be using `StateCreator` apart from middlewares? So I can understand how much migration we will save when we introduce defaults.

Comment (dai-shi) [reply src/vanilla.ts:32]: You understand what I mean correctly.

Yeah, I'm not quite sure either how many users depend on `StateCreator` type.
It's me that introduced the `Custom` things and it doesn't work well as I originally hoped.
And, this PR fixes it.

So, I now feel like this can be a new type, like you did so in #662.
How about deprecating `StateCreator` in v3 (#715)?
```ts
/**
 * @deprecated `StateCreator` is deprecated and will be removed in v4.
 * If necessary, please define it on your end.
 * type StateCreator<T extends State> = (set: SetState<T>, get: GetState<T>, api: StoreApi<T>) => T
 * /
```

And, in v4 (#725), we use a new name. I would say `CreateState`, but your original suggestion `StoreInitializer` is possible.

Comment (devanshj) [reply src/vanilla.ts:32]: I don't think that solves the problem. For example users might be using `StateCreator` while [creating slices that the wiki suggests](https://github.com/pmndrs/zustand/wiki/Splitting-the-store-into-separate-slices). This is a legitimate usecase of `StateCreator`, if we deprecate it they'll define their own `StateCreator` in meantime and then again in v4 they'll have to use the new `CreateState`/`StoreIntializer` type. All this is a little messy.

I think in this case it's okay to have the `= []` defaults, they seem reasonable. It won't remove the necessity of migration, there's no way to escape breaking changes, the best we can do is making them minimal which the defaults do.

Comment (dai-shi) [reply src/vanilla.ts:32]: Okay, then. Let's go with `= []`.

File: src/react.ts [hunk 12]
```diff
@@ -2,18 +2,17 @@ import { useDebugValue } from 'react'
...
   StateSelector,
   StoreApi,
+  StoreMutatorIdentifier,
 } from './vanilla'
 
-export function useStore<T extends State>(api: StoreApi<T>): T
-export function useStore<T extends State, U>(
-  api: StoreApi<T>,
-  selector: StateSelector<T, U>,
+export function useStore<S extends StoreApi<State>, U = ExtractState<S>>(
```
Comment (dai-shi) [inline src/react.ts:13]: I thinks it's rare that people specify `useStore<MyState>(...)`, but as this is a breaking change, it's worth noting in release note. Can you create a summary of public type changes in the description of this PR please?

File: src/react.ts [hunk 13]
```diff
@@ -2,18 +2,17 @@ import { useDebugValue } from 'react'
...
+  api: S,
+  selector?: StateSelector<ExtractState<S>, U>,
```
Comment (dai-shi) [inline src/react.ts:15]: Oh, I see. We actually support undefined selector with defined equalityFn.

(I didn't know `StateSelector<ExtractState<S>, U>` is possible with `U=...`. TIL)

File: src/react.ts [hunk 14]
```diff
@@ -32,42 +31,28 @@ export function useStore<TState extends State, StateSlice>(
...
-  TState extends State,
-  CustomSetState,
-  CustomGetState,
-  CustomStoreApi extends StoreApi<TState>
->(
-  createState:
-    | StateCreator<TState, CustomSetState, CustomGetState, CustomStoreApi>
-    | CustomStoreApi
-): UseBoundStore<TState, CustomStoreApi>
+export type UseBoundStore<S> = (<U = ExtractState<S>>(
```
Comment (dai-shi) [inline src/react.ts:36]: Same for this. Rare but type breaking.

File: src/react.ts [hunk 15]
```diff
@@ -32,42 +31,28 @@ export function useStore<TState extends State, StateSlice>(
...
-  createState:
-    | StateCreator<TState, CustomSetState, CustomGetState, CustomStoreApi>
-    | CustomStoreApi
-): UseBoundStore<TState, CustomStoreApi> {
-  const api: CustomStoreApi =
+  <T extends State>(): <Mos extends [StoreMutatorIdentifier, unknown][] = []>(
+    initializer: StateCreator<T, [], Mos>
+  ) => UseBoundStore<Mutate<StoreApi<T>, Mos>>
+  <S extends StoreApi<State>>(store: S): UseBoundStore<S>
+}
```
Comment (dai-shi) [inline src/react.ts:52]: Cool. (but this will be very difficult for first comers.)

**Review by dai-shi — COMMENTED** [review]
I think you have some action items to work with latest comments.

Meanwhile, I reviewed `react.ts`. It looks good to me.

File: src/react.ts (hunk 12 above)
Comment (devanshj) [reply src/react.ts:13]: Yes it indeed is a breaking change. Sure, I'll create a summary soon.

File: src/react.ts (hunk 13 above)
Comment (devanshj) [reply src/react.ts:15]: > We actually support undefined selector with defined equalityFn.

Yes that would work with these types. (Also at the end I'll add `| undefined` to all optional signatures)

> U=...

Haha yeah with that you don't need overloads

Comment (dai-shi) [reply src/react.ts:15]: > Also at the end I'll add `| undefined` to all optional signatures

Why do you need it? I usually don't add it for simplicity.

Comment (devanshj) [reply src/react.ts:15]: So that it works for people who have `--exactOptionalProperties` on. For example this won't compile if you have it on...

```ts
declare const foo: (a: number, b?: number) => void

foo(1, undefined)
```

Comment (dai-shi) [reply src/react.ts:15]: Hmm, in my mind, that's something I want to have an error, if there's such an option.

exactOptionalProperties only works on properties, and not function parameters? https://tsplay.dev/wQeZJw

Comment (devanshj) [reply src/react.ts:15]: > Hmm, in my mind, that's something I want to have an error, if there's such an option.

But then passing `undefined` as selector and some value as equalityFn won't work.

> exactOptionalProperties only works on properties, and not function parameters? https://tsplay.dev/wQeZJw

Ah interesting, then there's no point of add `| undefined` to parameters

Comment (dai-shi) [reply src/react.ts:15]: > But then passing `undefined` as selector and some value as equalityFn won't work.

Ah, I see. That makes sense. Anyway, for now, we don't need to add `| undefined`.

File: src/middleware/subscribeWithSelector.ts [hunk 16]
```diff
@@ -1,43 +1,62 @@
...
+  Mcs extends [StoreMutatorIdentifier, unknown][] = []
+>(
+  initializer: StateCreator<
+    T,
+    [...Mps, ['zustand/subscribeWithSelector', never]],
+    Mcs
+  >
+) => StateCreator<T, Mps, [['zustand/subscribeWithSelector', never], ...Mcs]>
+
+declare module '../vanilla' {
```
Comment (dai-shi) [inline src/middleware/subscribeWithSelector.ts:22]: Ah, I bet this does the trick of overloading the interface.

File: src/middleware/subscribeWithSelector.ts [hunk 17]
```diff
@@ -1,43 +1,62 @@
...
-  (
-    set: CustomSetState,
-    get: CustomGetState,
-    api: CustomStoreApi & StoreApiWithSubscribeWithSelector<S>
-  ): S => {
+type WithSelectorSubscribe<S> = S extends { getState: () => infer T }
+  ? S & StoreSubscribeWithSelector<Extract<T, State>>
+  : never
+
+interface StoreSubscribeWithSelector<T extends State> {
```
Comment (dai-shi) [inline src/middleware/subscribeWithSelector.ts:33]: Can this be type alias?

File: src/middleware/subscribeWithSelector.ts [hunk 18]
```diff
@@ -1,43 +1,62 @@
...
+    selector: (state: T) => U,
+    listener: (selectedState: U, previousSelectedState: U) => void,
+    options?: {
+      equalityFn?: (a: U, b: U) => boolean
+      fireImmediately?: boolean
+    }
+  ) => () => void
+}
+
+export type StoreApiWithSubscribeWithSelector<T extends State> =
```
Comment (dai-shi) [inline src/middleware/subscribeWithSelector.ts:44]: Do we need to export this type? Does a user need to use this for explicit typing?

**Review by dai-shi — COMMENTED** [review]
Just reviewed subscribeWithSelector. Fairly readable. Thanks for minimizing the diff.

I'm slowly reviewing diffs, while waiting for your changes based on previous comments.
We don't rush for v4 yet, but should prepare v3.7.0 sooner or later.

File: src/middleware/subscribeWithSelector.ts (hunk 16 above)
Comment (devanshj) [reply src/middleware/subscribeWithSelector.ts:22]: Yep

File: src/middleware/subscribeWithSelector.ts (hunk 17 above)
Comment (devanshj) [reply src/middleware/subscribeWithSelector.ts:33]: It can be but I prefer interfaces wherever possible for better quickinfo tooltips and error messages.

File: src/middleware/subscribeWithSelector.ts (hunk 18 above)
Comment (devanshj) [reply src/middleware/subscribeWithSelector.ts:44]: Nope, I'd prefer this to not be exported. But I kept it exported (it's already exported in v3) to avoid breaking changes.

We can deprecated this, in favor of writing `Mutate<Store<T>, ["zustsnd/subscribeWithSelector"]>` instead.

File: src/middleware/subscribeWithSelector.ts (hunk 17 above)
Comment (dai-shi) [reply src/middleware/subscribeWithSelector.ts:33]: I prefer type aliases when we don't intend to overload to avoid accidental overloading (but I know this is not very popular opinion and controversial.)
I didn't know about the difference in tooltips/messages.

File: src/context.ts [hunk 19]
```diff
@@ -14,27 +14,24 @@ import {
...
+type ExtractState<S> = S extends { getState: () => infer T } ? T : never
 
-function createContext<
-  TState extends State,
-  CustomStoreApi extends StoreApi<TState> = StoreApi<TState>
->() {
-  const ZustandContext = reactCreateContext<CustomStoreApi | undefined>(
-    undefined
-  )
+function createContext<S extends StoreApi<State>>() {
```
Comment (dai-shi) [inline src/context.ts:24]: This type change may break existing app code. Hope we can give migration path in v3.7.0. Can we do that in #715?

File: src/context.ts [hunk 20]
```diff
@@ -14,27 +14,24 @@ import {
   useStore,
 } from 'zustand'
 
-export type UseContextStore<T extends State> = {
-  (): T
-  <U>(selector: StateSelector<T, U>, equalityFn?: EqualityChecker<U>): U
-}
+export type UseContextStore<S> = <U = ExtractState<S>>(
```
Comment (dai-shi) [inline src/context.ts:17]: Since, that type is changed. We can rename the new one and deprecate the old one in #715?

File: src/context.ts [hunk 21]
```diff
@@ -59,30 +56,26 @@ function createContext<
...
-        subscribe: store.subscribe,
-        destroy: store.destroy,
-      }),
+      () =>
+        ({
+          getState: store.getState,
+          setState: store.setState,
+          subscribe: store.subscribe,
+          destroy: store.destroy,
+        } as S),
```
Comment (dai-shi) [inline src/context.ts:78]: `as S` seems wrong here. We don't even need any type assertion?

**Review by dai-shi — COMMENTED** [review]
Just reviewed `context.ts`. It generally looks good. Added some comments.

@devanshj I hope you will be back soon!

File: src/middleware/subscribeWithSelector.ts (hunk 17 above)
Comment (devanshj) [reply src/middleware/subscribeWithSelector.ts:33]: Not here but usually there is a considerable amount of performance benefit too, as with interface typescript knows it will strictly be an object, with type alias it can be anything—unions, intersections, conditions, etc.

Should we go with interfaces? The biggest benefit is with error messages.

File: src/middleware/subscribeWithSelector.ts (hunk 18 above)
Comment (devanshj) [reply src/middleware/subscribeWithSelector.ts:44]: > We can't give migration path in v3.7.0 unfortunately.

We can give a partial migration path by having `Mutate` (just `Mutate` no changes in `create` etc) in v3.7.0 itself and deprecate the old type(s). I'll open a PR in a few days if that's okay.

**Comment by devanshj** [comment]
> @devanshj I hope you will be back soon!

Sorry somehow I missed this notification 😅 and was also working on my blog

File: src/middleware/subscribeWithSelector.ts (hunk 17 above)
Comment (dai-shi) [reply src/middleware/subscribeWithSelector.ts:33]: I wasn't aware about the performance benefit with being an object.

Well, I may change my ming in the future, but let's keep it an interface for this PR.
(I need to experiment the error message difference to better understand.)

File: src/context.ts (hunk 21 above)
Comment (devanshj) [reply src/context.ts:78]: Hmm if I remember correctly this was so that the inferred type shows `S` and not `{ getState: S["getState"], ... }` etc. But then we have already annotated the return type with `:S` so this probably is not required, will recheck.

File: src/context.ts (hunk 19 above)
Comment (devanshj) [reply src/context.ts:24]: We can probably add an overload of the older type, so yes we can have a migration path in v3.7.0

File: src/context.ts (hunk 20 above)
Comment (devanshj) [reply src/context.ts:17]: I'm not sure about renaming the new one (as the current name is good), what we can do is we can handle both cases...

```
type UseContextStore<T extends State | Store<State>> = 
  <U = T extends Store<State> ? ExtractState<T> : T>(
    selector?: (state: ExtractState<S>) => U,
    equals?: (a: U, b: U) => boolean
  ) => U
```

A little hacky but I think it'll work. Wdyt?

File: src/middleware/subscribeWithSelector.ts (hunk 18 above)
Comment (devanshj) [reply src/middleware/subscribeWithSelector.ts:44]: Did it, see #772 to know what I mean

File: src/context.ts (hunk 20 above)
Comment (devanshj) [reply src/context.ts:17]: Made this change in #772, will revert if we're doing something else

File: src/context.ts (hunk 21 above)
Comment (devanshj) [reply src/context.ts:78]: Also look like I've accidently deleted `return { Provider, useStore: useBoundStore, useStoreApi }`? Because it in the [base branch](https://github.com/pmndrs/zustand/blob/v4/src/context.ts#L90-L94), but then why the diff doesn't show I deleted it? I'm so confused rn, probably I should sleep xD

File: src/context.ts (hunk 20 above)
Comment (dai-shi) [reply src/context.ts:17]: I will look into it. We want to mark `@deprecated` to the old usage.

File: src/context.ts (hunk 21 above)
Comment (dai-shi) [reply src/context.ts:78]: This should be `{ getState: S["getState"], ... }` because we want to avoid the function call usage.

**Comment by dai-shi** [comment]
@devanshj Hi, do you have a chance to continue this and #772? I hope to release v3.7 in a few weeks or before that. I think we need to agree on #725 first to complete #722.

**Comment by devanshj** [comment]
As I said before this is 99% complete, could you review it all at once? I don't have a lot time to invest in this, so making small changes multiple times is not something that's possible, I hope you'd understand.

Once you review it completely, I'd make the changes you'd request and then this would be good to go.

**Comment by dai-shi** [comment]
No, I definitely didn't know your status. I thought you have been busy and I have waited for a long period.

Okay, I'm not confident if this will finish in one cycle. (Maybe not technical ones. If you don't have time I can take this PR over for non technical ones.)
But anyway, I will try to finish reviewing soon (I think mostly fine too, but there will be many small ones.)
Meanwhile, can you check the lint and the test? That was the major reason why I didn't take it seriously. Are you sure if they are all trivial things?

File: src/context.ts (hunk 20 above)
Comment (dai-shi) [reply src/context.ts:17]: We agree to stop exporting this type.

File: tests/middlewareTypes.test.tsx [hunk 22]
```diff
@@ -72,7 +34,7 @@ describe('counter state spec (no middleware)', () => {
 
 describe('counter state spec (single middleware)', () => {
   it('immer', () => {
-    const useStore = create<CounterState>(
+    const useStore = create<CounterState>()(
```
Comment (dai-shi) [inline tests/middlewareTypes.test.tsx:37]: Yeah, this is truly magical, I wonder if people would like it or not.
In JS, we don't need this right?
What if people want the v3 style, with explicit typing, would it be possible? I'd like to have such an option too.

**Review by dai-shi — CHANGES_REQUESTED** [review]
Hey, just reviewed remaining files. I feel like I would need at least two more review cycles. Please bare with me.
We are now getting into some coding styles. Please fix CI tests too.

File: src/react.ts [hunk 23]
```diff
@@ -32,42 +31,28 @@ export function useStore<TState extends State, StateSlice>(
...
-function create<TState extends State>(
-  createState:
-    | StateCreator<TState, SetState<TState>, GetState<TState>, any>
-    | StoreApi<TState>
-): UseBoundStore<TState, StoreApi<TState>>
+type Create = {
+  <T extends State, Mos extends [StoreMutatorIdentifier, unknown][] = []>(
+    initializer: StateCreator<T, [], Mos>
+  ): UseBoundStore<Mutate<StoreApi<T>, Mos>>
+  <S extends StoreApi<State>>(store: S): UseBoundStore<S>
```
Comment (dai-shi) [inline src/react.ts:46]: This line is duplicates with L51?

File: tests/middlewareTypes.test.tsx (hunk 22 above)
Comment (dai-shi) [reply tests/middlewareTypes.test.tsx:37]: The type seems to support it. Can you add at least one example in this file please?
Maybe, subscribeWithSelector + persist combo would be a good example.

**Comment by dai-shi** [comment]
@devanshj Looking it again, this is exciting. Please invest time on this to finished it up. docs will be crucial (can be a separate PR).

**Comment by devanshj** [comment]
> No, I definitely didn't know your status. I thought you have been busy and I have waited for a long period.
> 
> Okay, I'm not confident if this will finish in one cycle. (Maybe not technical ones. If you don't have time I can take this PR over for non technical ones.) But anyway, I will try to finish reviewing soon (I think mostly fine too, but there will be many small ones.) Meanwhile, can you check the lint and the test? That was the major reason why I didn't take it seriously. Are you sure if they are all trivial things?

Ah looks like you must have missed [this comment](https://github.com/pmndrs/zustand/pull/725#issuecomment-1008102464), it's okay I should have made it clear that I'm waiting for review.

I don't mind if it takes multiple cycles as long as we're doing things in one streak. I think I missed looking at the CI but they're trivial, I'll fix it.

File: src/context.ts (hunk 21 above)
Comment (devanshj) [reply src/context.ts]: > Yes, because the goal of this is to avoid misusage of hooks. S contains a hook, and we want to not expose it.

Gotcha, fixed it although I added a type `WithoutCallSignaure<S>` so that the tooltip is more readable, otherwise it'll show `{ getState: S["getState"], ... }`, I'll revert it you don't like it.

File: src/context.ts (hunk 19 above)
Comment (devanshj) [reply src/context.ts:21]: We can keep it but I think the newer version is better because it encourages users to pass the store type instead of the state type. If they pass the state type, then when they use `useStoreApi()` they'd get the default store instead of the one they would have passed to the provider with middlewares. I hope I've made myself clear. Let me know if you want me to revert it.

File: src/context.ts (hunk 20 above)
Comment (devanshj) [reply src/context.ts]: First I mistakenly removed it entirely but now I'm keeping it just won't export it (so that the tooltip is a better)

File: src/middleware/devtools.ts [hunk 24]
```diff
@@ -17,326 +18,201 @@ type DevtoolsType = {
...
+  Mps extends [StoreMutatorIdentifier, unknown][] = [],
+  Mcs extends [StoreMutatorIdentifier, unknown][] = [],
+  U = Partial<T>
+>(
+  initializer: StateCreator<T, [...Mps, ['zustand/devtools', unknown]], Mcs>,
+  options?: DevtoolsOptions
+) => StateCreator<T, Mps, [['zustand/devtools', U], ...Mcs]>
+
+declare module '../vanilla' {
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
```
[the remark this answers is not in the document]
Comment (devanshj) [reply src/middleware/devtools.ts:32]: I think this is a good rule as it also applies to runtime unused variables. This case is a rare one so I think it's okay to suppress the warning instead of removing the rule entirely.

File: src/middleware/devtools.ts [hunk 25]
```diff
@@ -17,326 +18,201 @@ type DevtoolsType = {
...
-      )
-      didWarnAboutNameDeprecation = true
-    }
-    const devtoolsOptions =
-      options === undefined
-        ? { name: undefined, anonymousActionType: undefined }
-        : typeof options === 'string'
-        ? { name: options }
-        : options
+export type WithDevtools<S> = Write<
```
[the remark this answers is not in the document]
Comment (devanshj) [reply src/middleware/devtools.ts:58]: We don't have to as users can use `Mutate` but I think it's okay to export it. We can choose to not export it too I don't mind.

File: src/middleware/immer.ts [hunk 26]
```diff
@@ -0,0 +1,67 @@
...
+) => StateCreator<T, Mps, [['zustand/immer', never], ...Mcs]>
+
+declare module 'zustand' {
+  // eslint-disable-next-line @typescript-eslint/no-unused-vars
+  interface StoreMutators<S, A> {
+    ['zustand/immer']: WithImmer<S>
+  }
+}
+
+export type WithImmer<S> = S extends {
```
[the remark this answers is not in the document]
Comment (devanshj) [reply src/middleware/immer.ts:20]: Yes, we should deprecate `StoreWithDevtools` (and all other equivalent types that take state type instead of store type as parameter) and not export them in v4. I'll make that change in #772 too.

File: src/middleware/persist.ts [hunk 27]
```diff
@@ -124,188 +131,207 @@ const toThenable =
...
+  options?: PersistOptions<T, U>
+) => StateCreator<T, Mps, [['zustand/persist', U], ...Mcs]>
+
+declare module '../vanilla' {
+  interface StoreMutators<S, A> {
+    'zustand/persist': WithPersist<S, A>
   }
+}
+
+type WithPersist<S, A> = S extends { getState: () => infer T }
```
[the remark this answers is not in the document]
Comment (devanshj) [reply src/middleware/persist.ts:319]: I probably missed exporting it, will do.

File: tests/middlewareTypes.test.tsx (hunk 22 above)
Comment (devanshj) [reply tests/middlewareTypes.test.tsx:37]: > Yeah, this is truly magical, I wonder if people would like it or not.

I think TS people would like it as they don't have to manually pass the complex middlewared store types.

> In JS, we don't need this right?

Yes, although it would be preferred for better intellisense.

> What if people want the v3 style, with explicit typing, would it be possible? I'd like to have such an option too.
> The type seems to support it. Can you add at least one example in this file please?
> Maybe, subscribeWithSelector + persist combo would be a good example.

Yep it's possible I'll add a test case

File: src/react.ts (hunk 23 above)
Comment (devanshj) [reply src/react.ts:46]: Ah yes it's a duplicate overload, I'll remove it.

File: src/middleware/devtools.ts [hunk 28]
```diff
@@ -17,326 +18,201 @@ type DevtoolsType = {
...
+    (window as any).__REDUX_DEVTOOLS_EXTENSION__ ||
+    (window as any).top.__REDUX_DEVTOOLS_EXTENSION__
 
-            case 'ROLLBACK':
-              return parseJsonThen<S>(message.state, (state) => {
-                setStateFromDevtools(state)
-                extension.init(api.getState())
-              })
+  if (!extensionConnector) {
+    if (process.env.NODE_ENV === 'development') {
```
[the remark this answers is not in the document]
Comment (devanshj) [reply src/middleware/devtools.ts]: Fixed it, I hope now it's okay.

**Comment by dai-shi** [comment]
Please "Re-request revew", when it's ready.

**Comment by devanshj** [comment]
There's one test failing I'm not sure why 🤔 Could you give it a look?

File: src/context.ts (hunk 19 above)
Comment (dai-shi) [reply src/context.ts:26]: Yes, i agree the new one is better.

File: src/context.ts [hunk 29]
```diff
@@ -59,30 +58,26 @@ function createContext<
...
-        subscribe: store.subscribe,
-        destroy: store.destroy,
-      }),
+      () =>
+        ({
+          getState: store.getState,
+          setState: store.setState,
+          subscribe: store.subscribe,
+          destroy: store.destroy,
+        } as WithoutCallSignature<S>),
```
Comment (dai-shi) [inline src/context.ts:80]: I see. This should work.

File: src/middleware/devtools.ts [hunk 30]
```diff
@@ -17,326 +18,212 @@ type DevtoolsType = {
...
+
+  if (
+    (api as any).dispatchFromDevtools &&
+    typeof (api as any).dispatch === 'function'
+  ) {
+    let didWarnAboutReservedActionType = false
+    const originalDispatch = ((api as any).dispatch(api as any).dispatch = (
+      ...a: any[]
+    ) => {
+      if (a[0].type === '__setState' && !didWarnAboutReservedActionType) {
```
Comment (dai-shi) [inline src/middleware/devtools.ts:213]: We will be able to use `__DEV__`. We can use it to only warn in the development mode.
Also, I wonder if we can/should eliminate `didWarnAboutReservedActionType` and warn many times.

File: src/middleware/devtools.ts [hunk 31]
```diff
@@ -17,326 +18,212 @@ type DevtoolsType = {
...
-        console.warn(
-          '[zustand devtools middleware] Please install/enable Redux devtools extension'
-        )
-      }
-      return fn(set, get, api)
+type StoreSetStateWithAction<S> = S extends {
+  setState: (...a: infer A) => infer R
+}
+  ? {
+      setState: (...a: [...a: A, actionType?: string | { type: unknown }]) => R
```
Comment (dai-shi) [inline src/middleware/devtools.ts:67]: :eye: (I can read it...)

File: src/middleware/immer.ts [hunk 32]
```diff
@@ -0,0 +1,67 @@
...
+              nextStateOrUpdater: Nt | ((state: Draft<T>) => void),
+              shouldReplace?: R,
+              ...a: A
+            ) => Sr
+          : never
+      }
+    >
+  : never
+
+type Write<T extends object, U extends object> = Omit<T, keyof U> & U
```
Comment (dai-shi) [inline src/middleware/immer.ts:40]: move up please.

File: src/vanilla.ts [hunk 33]
```diff
@@ -104,12 +98,23 @@ function createStore<
...
   )
-  return api as unknown as CustomStoreApi
+  return api as any
 }
 
+type PopArgument<T extends (...a: never[]) => unknown> = T extends (
+  ...a: [...infer A, infer _]
+) => infer R
+  ? (...a: A) => R
+  : never
```
Comment (dai-shi) [inline src/vanilla.ts:113]: move up.

File: tests/middlewareTypes.test.tsx [hunk 34]
```diff
@@ -665,3 +557,41 @@ describe('more complex state spec with subscribeWithSelector', () => {
...
+
+describe('create with explicitly annotated mutators', () => {
+  it('subscribeWithSelector & persist', () => {
+    const useStore = create<
+      CounterState,
+      [
+        ['zustand/subscribeWithSelector', never],
+        ['zustand/persist', Partial<CounterState>]
+      ]
+    >(
```
Comment (dai-shi) [inline tests/middlewareTypes.test.tsx:569]: Thanks. I'm sure some people prefer this style.

We might need more patterns of combinations.

**Review by dai-shi — COMMENTED** [review]
Some minor comments for now.

I will look into tests.

**Review by dai-shi — CHANGES_REQUESTED** [review]
@devanshj v4 branch is updated, please follow the changes. sorry for the trouble. this should be the last time unless we need a patch release v3.7.x.

File: src/middleware/devtools.ts [hunk 35]
```diff
@@ -17,326 +18,212 @@ type DevtoolsType = {
...
-              'it will be removed in the next major.\n' +
-              "You shouldn't interact with the extension directly. But in case you still want to " +
-              'you can patch `window.__REDUX_DEVTOOLS_EXTENSION__` directly'
-          )
-          didWarnAboutDevtools = true
-        }
-        extension = value
-      },
-    })
+type PopArgument<T extends (...a: never[]) => unknown> = T extends (
```
[the remark this answers is not in the document]
Comment (devanshj) [reply src/middleware/devtools.ts:76]: It's there to make sure the parameter passed is a function eg `PopArgument<string>` won't compile, just like `ReturnType<string>` doesn't compile.

[the remark this answers is not in the document]
Comment (dai-shi) [reply src/middleware/devtools.ts:103]: Thanks!

File: src/middleware/redux.ts [hunk 36]
```diff
@@ -1,62 +1,59 @@
...
-
 interface Action {
   type: unknown
 }
 
-type Write<T extends object, U extends object> = Omit<T, keyof U> & U
-type Cast<T, U> = T extends U ? T : U
+interface ReduxState<A extends Action> {
+  dispatch: StoreRedux<A>['dispatch']
+}
```
Comment (dai-shi) [inline src/middleware/redux.ts:31]: Move up please. (sorry to bother..)

File: src/vanilla.ts [hunk 37]
```diff
@@ -113,22 +107,17 @@ function createStore<
...
+    api
   )
-  return api as unknown as CustomStoreApi
+  return api as any
 }
 
-export default createStore
+const createStore = ((f) => {
+  if (f === undefined) return createStoreImpl
+  return createStoreImpl(f)
```
Comment (dai-shi) [inline src/vanilla.ts:120]: This looks a bit different from `react.ts`.
Should we name it `createState` instead of `f` here too?
Also, if we make this ternary syntax, it may reduce bundle size (at least for ESM).
```ts
const createStore = ((createState) => (
  createState ? createImpl(createState) : createImpl
)) as CreateStore
```

File: tests/middlewareTypes.test.tsx (hunk 34 above)
Comment (dai-shi) [reply tests/middlewareTypes.test.tsx:611]: Yeah, I think we will need them eventually. But, it's fine for this PR.

**Review by dai-shi — CHANGES_REQUESTED** [review]
This looks much cleaner! Great.
Would you address small changes in comments,
and also work on breaking change notes (so that I can just copy&paste in release note)?
Once done, and unless we don't get bug reports for v3.7.0 for a week or so, I will merge everything, and release `-rc` version.

File: src/middleware/devtools.ts (hunk 30 above)
Comment (devanshj) [reply src/middleware/devtools.ts]: Yeah sorry forgot to address this one, yeah I'm using `__DEV__` now. Warning many times will might make the console too noisy for the user (and hence it might unnecessarily force them to fix this their first priority).

File: src/middleware/redux.ts (hunk 36 above)
Comment (devanshj) [reply src/middleware/redux.ts]: Yeah don't worry, feel free to tweak things yourself too if you wish.

File: src/vanilla.ts (hunk 37 above)
Comment (devanshj) [reply src/vanilla.ts]: Yep, renamed and using ternary now.

**Comment by devanshj** [comment]
> breaking change notes (so that I can just copy&paste in release note)?

Yep will do that soon. Also don't merge this yet I have to make some checks regarding types.

File: tests/devtools.test.tsx [hunk 38]
```diff
@@ -437,6 +439,8 @@ describe('when it receives an message of type...', () => {
 })
 
 it('works with redux middleware', () => {
```
Comment (dai-shi) [inline tests/devtools.test.tsx:441]: Here's the trick. Not super elegant, and hope to find a better way.
```suggestion
it('[DEV-ONLY] works with redux middleware', () => {
```

**Review by dai-shi — CHANGES_REQUESTED** [review]
Looks okay from my side.
The remaining is notes about breaking changes.

If you fix everything and ready for merge, please mark it "ready for review" from "draft".

**Comment by dai-shi** [comment]
One more thing: please check #812, which may affect v3.7.x and then this.

**Comment by devanshj** [comment]
(Just updating that I remember I'm yet to get back to this, I'll be back in a day or two)

**Comment by devanshj** [comment]
Looks like the some tests running with react 18 are failing, not sure why, @dai-shi could you check?

**Comment by dai-shi** [comment]
@devanshj I guess you failed to merge v4 properly. the important change is this: https://github.com/pmndrs/zustand/commit/d4b72002b9d1368975b294fc81835cc41c6e8851

**Comment by devanshj** [comment]
No I think I've got it right: https://github.com/devanshj/zustand/commit/d4b72002b9d1368975b294fc81835cc41c6e8851

You can even check the files:
https://github.com/devanshj/zustand/blob/b653b4b62bdd05efe05d751be6dd0f39d70ec50e/package.json#L185-L187
https://github.com/devanshj/zustand/blob/b653b4b62bdd05efe05d751be6dd0f39d70ec50e/yarn.lock#L2195-L2198

**Comment by dai-shi** [comment]
Oh, my bad then...

File: src/middleware/persist.ts [hunk 39]
```diff
@@ -5,19 +5,15 @@ import {
...
-}
-
 export type StateStorage = {
   getItem: (name: string) => string | null | Promise<string | null>
   setItem: (name: string, value: string) => void | Promise<void>
   removeItem: (name: string) => void | Promise<void>
 }
 
-type StorageValue<S> = { state: DeepPartial<S>; version?: number }
+type StorageValue<S> = { state: S; version?: number }
```
Comment (devanshj) [inline src/middleware/persist.ts:14]: There's no reason for this to be `DeepPartial<S>` so I made it `S`.

File: src/middleware/persist.ts [hunk 40]
```diff
@@ -5,19 +5,15 @@ import {
...
 
-export type PersistOptions<S, PersistedState = Partial<S>> = {
+export type PersistOptions<S, PersistedState = S> = {
```
Comment (devanshj) [inline src/middleware/persist.ts:16]: Here again the types are lying, the default persisted state when no partialize is provided is the whole state ie S and not Partial<S>.

File: src/middleware/persist.ts [hunk 41]
```diff
@@ -66,12 +64,12 @@ export type PersistOptions<S, PersistedState = Partial<S>> = {
    * A function to perform persisted state migration.
    * This function will be called when persisted state versions mismatch with the one specified here.
    */
-  migrate?: (persistedState: any, version: number) => S | Promise<S>
+  migrate?: (persistedState: unknown, version: number) => S | Promise<S>
```
Comment (devanshj) [inline src/middleware/persist.ts:67]: `unknown` is preferred over `any`.

File: src/middleware/persist.ts [hunk 42]
```diff
@@ -66,12 +64,12 @@ export type PersistOptions<S, PersistedState = Partial<S>> = {
...
   /**
    * A function to perform custom hydration merges when combining the stored state with the current one.
    * By default, this function does a shallow merge.
    */
-  merge?: (persistedState: any, currentState: S) => S
+  merge?: (persistedState: unknown, currentState: S) => S
```
Comment (devanshj) [inline src/middleware/persist.ts:72]: Same here `unknown` is preferred over `any`.

**Review by dai-shi — CHANGES_REQUESTED** [review]
One request for change.

For `persist`, I want @AnatoleLucet to review it too.

For the release note, I think I can write the overall change and your draft helps. So, thanks for it.
What I would like you to work is:
a) Precise breaking changes of this PR (let's write them in the PR description)
b) Migration guide (let's create a new md file like `./v4-migration.md`.)
c) Create a new "TypeScript" section in readme.md and show our recommended usage (combining existing typescript-related descriptions. note that we prefer compact readme. So, prefer to have more description in b). I can actually work on c) from b), if you are busy.)

b) and c) can be separate PRs.

File: src/middleware/persist.ts (hunk 39 above)
Comment (AnatoleLucet) [reply src/middleware/persist.ts:14]: Not sure to understand what you mean by "the types are lying" 🤔 
Does it work with `partialize`?

File: src/middleware/persist.ts (hunk 41 above)
Comment (AnatoleLucet) [reply src/middleware/persist.ts:67]: Is it possible that `unkown` causes some type errors when trying to access `persistedState`'s properties?

**Review by AnatoleLucet — COMMENTED** [review]
Looking really nice 🚀

File: src/middleware/devtools.ts [hunk 43]
```diff
@@ -60,313 +57,175 @@ type DevtoolsType = {
...
+      ? { name: options }
+      : options
 
-    const initialState = fn(api.setState, get, api)
-    extension.init(initialState)
+  let extensionConnector
+  try {
+    extensionConnector =
+      (window as any).__REDUX_DEVTOOLS_EXTENSION__ ||
+      (window as any).top.__REDUX_DEVTOOLS_EXTENSION__
```
[the remark this answers is not in the document]
Comment (devanshj) [reply src/middleware/devtools.ts]: Yeah probably mistake while merging

File: src/middleware/persist.ts (hunk 39 above)
Comment (devanshj) [reply src/middleware/persist.ts:14]: > Not sure to understand what you mean by "the types are lying" 🤔

What I mean is types are not in alignment with the runtime. In runtime we're storing `{ state: S, version?: number }` in the storage but the types say we're storing `{ state: DeepPartial<S>, version?: number }` hence they're lying.

> Does it work with partialize?

Yes it does, I'll add a test case

File: src/middleware/persist.ts (hunk 41 above)
Comment (devanshj) [reply src/middleware/persist.ts:67]: Yes it does, that's the point of the change. `persistedState` comes from the (local)storage so it can be anything (hence `unknown`) the users should responsibly handle it.

**Comment by devanshj** [comment]
I've updated the readme. Will write the breaking changes in the description soon.

File: src/middleware/immer.ts [hunk 44]
```diff
@@ -0,0 +1,66 @@
...
+const immerImpl: ImmerImpl = (initializer) => (set, get, store) => {
+  type T = ReturnType<typeof initializer>
+  const immerSetState: typeof set = (updater, replace) => {
+    const nextState = (
+      typeof updater === 'function' ? produce(updater as any) : updater
+    ) as ((s: T) => T) | T | Partial<T>
+
+    return set(nextState as any, replace)
+  }
+  const s = initializer(immerSetState, get, store)
```
Comment (devanshj) [inline src/middleware/immer.ts:61]: It's important to call `initializer` before we mutate `store` so that the mutations that are innermost happen first.

**Comment by devanshj** [comment]
Also do you really want me to write the breaking changes? I mean because almost everything is a breaking change. For example even something as trivial as the `redux` middleware: Imagine if someone is passing the type parameters, then the `Cms` will get fixated to `[]` (as that's the default) instead of getting inferred from contextual inference. Writing all breaking changes will be tedious for me.

I think it's possible to make a migration guide from the readme I just made and looking at the source. The migration guide should be less of "If you're doing X then now do Y" and more of "Just do Y" because doing Y is really simple.

**Comment by dai-shi** [comment]
@devanshj Thanks for working on this. We are almost there. (I'll review diffs later.)

> Writing all breaking changes will be tedious for me.

Hmm, that's unfortunate. Then, please write down all changes in terms of JS code (after tsc emitting).
For type changes, let's do it in b) `./v4-migration.md` as you suggest (and we'll keep improving it).

> a) Precise breaking changes of this PR (let's write them in the PR description)
> b) Migration guide (let's create a new md file like ./v4-migration.md.)
> c) Create a new "TypeScript" section in readme.md and show our recommended usage (combining existing typescript-related descriptions.

File: src/middleware/immer.ts (hunk 44 above)
Comment (dai-shi) [reply src/middleware/immer.ts:61]: Maybe we should add it in the code comment?

**Review by dai-shi — CHANGES_REQUESTED** [review]
Thanks for the write up! And, it gives me an idea. Please see comments.

File: src/middleware/immer.ts (hunk 44 above)
Comment (devanshj) [reply src/middleware/immer.ts]: I realized I got it backwards, the mutation should happen first (as it happens first with all other middlewares). Now the code is more obvious than before, so now should I still put a comment like the following or it's okay to skip it?

```ts
store.setState = (updater, replace) => {
  // ...
}
// We mutate the store first before calling `initializer`
// as we want the inner ("child") mutations to happen later.
// This is also indicated in the type, `immer` returns
// `StateCreator<T, Mps, [['zustand/immer', never], ...Mcs]>`,
// ie `...Mcs` (child mutators) is after `['zustand/immer', never]`
// This is true for all Zustand middlewares btw.

return initializer(store.setState, get, store)
```

File: readme.md [hunk 45]
```diff
@@ -586,43 +532,216 @@ const Component = () => {
...
-const useStore = create<BearState>(set => ({
+create<BearState>()((set) => ({
   bears: 0,
-  increase: (by) => set(state => ({ bears: state.bears + by })),
+  increase: () => set((state) => ({ bears: state.bears + 1 })),
 }))
 ```
 
-Or, use `combine` and let tsc infer types. This merges two states shallowly.
+<details>
```
[the remark this answers is not in the document]
Comment (devanshj) [reply readme.md:555]: I think a separate readme for typescript is a little unnecessary, as the "extra info" bits are already collapsed. Having a separate file for typescript makes it look as if the typescript usage is complex, when it's not (it's just the extra infos are a little long). What do you think? Should I still make a separate md for typescript?

> the usage with manual typing

I'd not want to mention this entirely, because it's not recommended. (You see generics in a way are implementation details so they should be as inferred as possible. If the generics are inferred it means we can make changes to the types and keep it non-breaking as long as the inference is the same but if users start passing unnecessary generics even if the inference is the same but a change in type-parameters make it breaking. So it's always recommended to not pass generics as much as possible.)

Also that's for v3 in v4 manual typing would look like this...

```ts
const useStore = create<
  BearState,
  [],
  [
    ['zustand/persist', BearState],
    ['zustand/devtools', never]
  ]
>(devtools(persist((set) => ({
  bears: 0,
  increase: (by) => set(state => ({ bears: state.bears + by })),
})))
```

> We should have Partial<BearState>, right?

No now the default is `BearState` for persist (as it should be)

**Comment by devanshj** [comment]
> Then, please write down all changes in terms of JS code (after tsc emitting).

There are no breaking changes on runtime level. Only two additions...
- `create` (from `zustand`, `zustand/vanilla` and `zustand/react` modules) now also takes zero arguments and returns the "actual" `create` that takes the store initializer. (This is a workaround for [microsoft/TypeScript#10571](https://github.com/microsoft/TypeScript/issues/10571))
- `zustand/middleware` module now also exports a `immer` middleware. This is to make the migration of users that have copy-pasted the immer middleware from `middlewareTypes.test.tsx` easier.

> For type changes, let's do it in b) ./v4-migration.md as you suggest (and we'll keep improving it).

Sure (and yes `./docs/v4-migration.md` as you suggested in the other comment)

File: readme.md (hunk 45 above)
[the remark this answers is not in the document]
Comment (dai-shi) [reply readme.md:555]: > I think a separate readme for typescript is a little unnecessary, as the "extra info" bits are already collapsed. Having a separate file for typescript makes it look as if the typescript usage is complex, when it's not (it's just the extra infos are a little long). What do you think? Should I still make a separate md for typescript?

Yes, I want to make a separate md.
I plan to move other contents to separate md files too. We want to make readme smaller than what we have now (collapsing is non-ideal workaround).
If you like, "extra info" can be collapsed too in the separate md, as it's very technical.

> > the usage with manual typing
> 
> I'd not want to mention this entirely, because it's not recommended.

I'm not 100% convinced, but we can start without manual typing. I expect some users want it (who don't like `()` workaround, or type inference). Yeah, I'm pretty sure about it. Some like to type store manually. When requested, we could add docs, but I'm afraid you are gone at that time.

> > We should have Partial, right?
> 
> No now the default is `BearState` for persist (as it should be)

Ah, I see. yeah, we changed it. Looks clean.

**Comment by dai-shi** [comment]
> There are no breaking changes on runtime level. Only two additions...

That's good. Would you be able to confirm by building v4 branch and this branch?

> Will continue tomorrow.

Looking forward to it!

**Comment by devanshj** [comment]
Did some updates, it's 90% complete now, will address the remaining things tomorrow.

**Comment by dai-shi** [comment]
> Would you be able to confirm by building v4 branch and this branch?

I just did this.

<details>
<summary>diff -ur dist-v4/esm dist/esm (js only)</summary>

```diff
diff -ur dist-v4/esm/context.js dist/esm/context.js
--- dist-v4/esm/context.js	2022-04-05 15:48:43.000000000 +0900
+++ dist/esm/context.js	2022-04-05 15:51:55.000000000 +0900
@@ -1,5 +1,11 @@
-import { createContext as createContext$1, useRef, createElement, useContext, useMemo } from 'react';
-import { useStore } from 'zustand';
+import { useDebugValue, createContext as createContext$1, useRef, createElement, useContext, useMemo } from 'react';
+import { useSyncExternalStoreWithSelector } from 'use-sync-external-store/shim/with-selector.js';
+
+function useStore(api, selector = api.getState, equalityFn) {
+  const slice = useSyncExternalStoreWithSelector(api.subscribe, api.getState, null, selector, equalityFn);
+  useDebugValue(slice);
+  return slice;
+}
 
 function createContext() {
   const ZustandContext = createContext$1(void 0);
diff -ur dist-v4/esm/index.js dist/esm/index.js
--- dist-v4/esm/index.js	2022-04-05 15:48:48.000000000 +0900
+++ dist/esm/index.js	2022-04-05 15:52:00.000000000 +0900
@@ -1,7 +1,7 @@
 import { useDebugValue } from 'react';
 import { useSyncExternalStoreWithSelector } from 'use-sync-external-store/shim/with-selector.js';
 
-function createStore(createState) {
+const createStoreImpl = (createState) => {
   let state;
   const listeners = /* @__PURE__ */ new Set();
   const setState = (partial, replace) => {
@@ -21,18 +21,22 @@
   const api = { setState, getState, subscribe, destroy };
   state = createState(setState, getState, api);
   return api;
-}
+};
+const createStore = (createState) => createState ? createStoreImpl(createState) : createStoreImpl;
+var createStore$1 = createStore;
 
 function useStore(api, selector = api.getState, equalityFn) {
   const slice = useSyncExternalStoreWithSelector(api.subscribe, api.getState, null, selector, equalityFn);
   useDebugValue(slice);
   return slice;
 }
-function create(createState) {
-  const api = typeof createState === "function" ? createStore(createState) : createState;
+const createImpl = (createState) => {
+  const api = typeof createState === "function" ? createStore$1(createState) : createState;
   const useBoundStore = (selector, equalityFn) => useStore(api, selector, equalityFn);
   Object.assign(useBoundStore, api);
   return useBoundStore;
-}
+};
+const create = (createState) => createState ? createImpl(createState) : createImpl;
+var create$1 = create;
 
-export { create as default, useStore };
+export { create$1 as default, useStore };
diff -ur dist-v4/esm/middleware.js dist/esm/middleware.js
--- dist-v4/esm/middleware.js	2022-04-05 15:48:44.000000000 +0900
+++ dist/esm/middleware.js	2022-04-05 15:51:56.000000000 +0900
@@ -1,3 +1,5 @@
+import { produce } from 'immer';
+
 var __defProp$1 = Object.defineProperty;
 var __getOwnPropSymbols$1 = Object.getOwnPropertySymbols;
 var __hasOwnProp$1 = Object.prototype.hasOwnProperty;
@@ -14,7 +16,7 @@
     }
   return a;
 };
-const redux = (reducer, initial) => (set, get, api) => {
+const reduxImpl = (reducer, initial) => (set, get, api) => {
   api.dispatch = (action) => {
     set((state) => reducer(state, action), false, action);
     return action;
@@ -22,140 +24,102 @@
   api.dispatchFromDevtools = true;
   return __spreadValues$1({ dispatch: (...a) => api.dispatch(...a) }, initial);
 };
+const redux = reduxImpl;
 
-function devtools(fn, options) {
-  return (set, get, api) => {
-    let didWarnAboutNameDeprecation = false;
-    if (typeof options === "string" && !didWarnAboutNameDeprecation) {
-      console.warn("[zustand devtools middleware]: passing `name` as directly will be not allowed in next majorpass the `name` in an object `{ name: ... }` instead");
-      didWarnAboutNameDeprecation = true;
-    }
-    const devtoolsOptions = options === void 0 ? {} : typeof options === "string" ? { name: options } : options;
-    let extensionConnector;
-    try {
-      extensionConnector = window.__REDUX_DEVTOOLS_EXTENSION__;
-    } catch {
-    }
-    if (!extensionConnector) {
-      if ((import.meta.env && import.meta.env.MODE) !== "production" && typeof window !== "undefined") {
-        console.warn("[zustand devtools middleware] Please install/enable Redux devtools extension");
-      }
-      return fn(set, get, api);
+const devtoolsImpl = (fn, options) => (set, get, api) => {
+  const devtoolsOptions = options === void 0 ? {} : typeof options === "string" ? { name: options } : options;
+  let extensionConnector;
+  try {
+    extensionConnector = window.__REDUX_DEVTOOLS_EXTENSION__;
+  } catch {
+  }
+  if (!extensionConnector) {
+    if ((import.meta.env && import.meta.env.MODE) !== "production" && typeof window !== "undefined") {
+      console.warn("[zustand devtools middleware] Please install/enable Redux devtools extension");
     }
-    let extension = Object.create(extensionConnector.connect(devtoolsOptions));
-    let didWarnAboutDevtools = false;
-    Object.defineProperty(api, "devtools", {
-      get: () => {
-        if (!didWarnAboutDevtools) {
-          console.warn("[zustand devtools middleware] `devtools` property on the store is deprecated it will be removed in the next major.\nYou shouldn't interact with the extension directly. But in case you still want to you can patch `window.__REDUX_DEVTOOLS_EXTENSION__` directly");
-          didWarnAboutDevtools = true;
-        }
-        return extension;
-      },
-      set: (value) => {
-        if (!didWarnAboutDevtools) {
-          console.warn("[zustand devtools middleware] `api.devtools` is deprecated, it will be removed in the next major.\nYou shouldn't interact with the extension directly. But in case you still want to you can patch `window.__REDUX_DEVTOOLS_EXTENSION__` directly");
-          didWarnAboutDevtools = true;
-        }
-        extension = value;
-      }
-    });
-    let didWarnAboutPrefix = false;
-    Object.defineProperty(extension, "prefix", {
-      get: () => {
-        if (!didWarnAboutPrefix) {
-          console.warn("[zustand devtools middleware] along with `api.devtools`, `api.devtools.prefix` is deprecated.\nWe no longer prefix the actions/names" + devtoolsOptions.name === void 0 ? ", pass the `name` option to create a separate instance of devtools for each store." : ", because the `name` option already creates a separate instance of devtools for each store.");
-          didWarnAboutPrefix = true;
-        }
-        return "";
-      },
-      set: () => {
-        if (!didWarnAboutPrefix) {
-          console.warn("[zustand devtools middleware] along with `api.devtools`, `api.devtools.prefix` is deprecated.\nWe no longer prefix the actions/names" + devtoolsOptions.name === void 0 ? ", pass the `name` option to create a separate instance of devtools for each store." : ", because the `name` option already creates a separate instance of devtools for each store.");
-          didWarnAboutPrefix = true;
-        }
-      }
-    });
-    let isRecording = true;
-    api.setState = (state, replace, nameOrAction) => {
-      set(state, replace);
-      if (!isRecording)
-        return;
-      extension.send(nameOrAction === void 0 ? { type: devtoolsOptions.anonymousActionType || "anonymous" } : typeof nameOrAction === "string" ? { type: nameOrAction } : nameOrAction, get());
-    };
-    const setStateFromDevtools = (...a) => {
-      const originalIsRecording = isRecording;
-      isRecording = false;
-      set(...a);
-      isRecording = originalIsRecording;
-    };
-    const initialState = fn(api.setState, get, api);
-    extension.init(initialState);
-    if (api.dispatchFromDevtools && typeof api.dispatch === "function") {
-      let didWarnAboutReservedActionType = false;
-      const originalDispatch = api.dispatch;
-      api.dispatch = (...a) => {
-        if (a[0].type === "__setState" && !didWarnAboutReservedActionType) {
-          console.warn('[zustand devtools middleware] "__setState" action type is reserved to set state from the devtools. Avoid using it.');
-          didWarnAboutReservedActionType = true;
+    return fn(set, get, api);
+  }
+  const extension = extensionConnector.connect(devtoolsOptions);
+  let isRecording = true;
+  api.setState = (state, replace, nameOrAction) => {
+    set(state, replace);
+    if (!isRecording)
+      return;
+    extension.send(nameOrAction === void 0 ? { type: devtoolsOptions.anonymousActionType || "anonymous" } : typeof nameOrAction === "string" ? { type: nameOrAction } : nameOrAction, get());
+  };
+  const setStateFromDevtools = (...a) => {
+    const originalIsRecording = isRecording;
+    isRecording = false;
+    set(...a);
+    isRecording = originalIsRecording;
+  };
+  const initialState = fn(api.setState, get, api);
+  extension.init(initialState);
+  extension.subscribe((message) => {
+    var _a;
+    switch (message.type) {
+      case "ACTION":
+        if (typeof message.payload !== "string") {
+          console.error("[zustand devtools middleware] Unsupported action format");
+          return;
         }
-        originalDispatch(...a);
-      };
-    }
-    extension.subscribe((message) => {
-      var _a;
-      switch (message.type) {
-        case "ACTION":
-          if (typeof message.payload !== "string") {
-            console.error("[zustand devtools middleware] Unsupported action format");
+        return parseJsonThen(message.payload, (action) => {
+          if (action.type === "__setState") {
+            setStateFromDevtools(action.state);
             return;
           }
-          return parseJsonThen(message.payload, (action) => {
-            if (action.type === "__setState") {
-              setStateFromDevtools(action.state);
-              return;
-            }
-            if (!api.dispatchFromDevtools)
-              return;
-            if (typeof api.dispatch !== "function")
-              return;
-            api.dispatch(action);
-          });
-        case "DISPATCH":
-          switch (message.payload.type) {
-            case "RESET":
-              setStateFromDevtools(initialState);
-              return extension.init(api.getState());
-            case "COMMIT":
-              return extension.init(api.getState());
-            case "ROLLBACK":
-              return parseJsonThen(message.state, (state) => {
-                setStateFromDevtools(state);
-                extension.init(api.getState());
-              });
-            case "JUMP_TO_STATE":
-            case "JUMP_TO_ACTION":
-              return parseJsonThen(message.state, (state) => {
-                setStateFromDevtools(state);
-              });
-            case "IMPORT_STATE": {
-              const { nextLiftedState } = message.payload;
-              const lastComputedState = (_a = nextLiftedState.computedStates.slice(-1)[0]) == null ? void 0 : _a.state;
-              if (!lastComputedState)
-                return;
-              setStateFromDevtools(lastComputedState);
-              extension.send(null, nextLiftedState);
+          if (!api.dispatchFromDevtools)
+            return;
+          if (typeof api.dispatch !== "function")
+            return;
+          api.dispatch(action);
+        });
+      case "DISPATCH":
+        switch (message.payload.type) {
+          case "RESET":
+            setStateFromDevtools(initialState);
+            return extension.init(api.getState());
+          case "COMMIT":
+            return extension.init(api.getState());
+          case "ROLLBACK":
+            return parseJsonThen(message.state, (state) => {
+              setStateFromDevtools(state);
+              extension.init(api.getState());
+            });
+          case "JUMP_TO_STATE":
+          case "JUMP_TO_ACTION":
+            return parseJsonThen(message.state, (state) => {
+              setStateFromDevtools(state);
+            });
+          case "IMPORT_STATE": {
+            const { nextLiftedState } = message.payload;
+            const lastComputedState = (_a = nextLiftedState.computedStates.slice(-1)[0]) == null ? void 0 : _a.state;
+            if (!lastComputedState)
               return;
-            }
-            case "PAUSE_RECORDING":
-              return isRecording = !isRecording;
+            setStateFromDevtools(lastComputedState);
+            extension.send(null, nextLiftedState);
+            return;
           }
-          return;
+          case "PAUSE_RECORDING":
+            return isRecording = !isRecording;
+        }
+        return;
+    }
+  });
+  if (api.dispatchFromDevtools && typeof api.dispatch === "function") {
+    let didWarnAboutReservedActionType = false;
+    const originalDispatch = api.dispatch;
+    api.dispatch = (...a) => {
+      if ((import.meta.env && import.meta.env.MODE) !== "production" && a[0].type === "__setState" && !didWarnAboutReservedActionType) {
+        console.warn('[zustand devtools middleware] "__setState" action type is reserved to set state from the devtools. Avoid using it.');
+        didWarnAboutReservedActionType = true;
       }
-    });
-    return initialState;
-  };
-}
+      originalDispatch(...a);
+    };
+  }
+  return initialState;
+};
+const devtools = devtoolsImpl;
 const parseJsonThen = (stringified, f) => {
   let parsed;
   try {
@@ -167,7 +131,7 @@
     f(parsed);
 };
 
-const subscribeWithSelector = (fn) => (set, get, api) => {
+const subscribeWithSelectorImpl = (fn) => (set, get, api) => {
   const origSubscribe = api.subscribe;
   api.subscribe = (selector, optListener, options) => {
     let listener = selector;
@@ -190,8 +154,9 @@
   const initialState = fn(set, get, api);
   return initialState;
 };
+const subscribeWithSelector = subscribeWithSelectorImpl;
 
-const combine = (initialState, create) => (set, get, api) => Object.assign({}, initialState, create(set, get, api));
+const combine = (initialState, create) => (...a) => Object.assign({}, initialState, create(...a));
 
 var __defProp = Object.defineProperty;
 var __getOwnPropSymbols = Object.getOwnPropertySymbols;
@@ -234,14 +199,14 @@
     };
   }
 };
-const persist = (config, baseOptions) => (set, get, api) => {
+const persistImpl = (config, baseOptions) => (set, get, api) => {
   let options = __spreadValues({
     getStorage: () => localStorage,
     serialize: JSON.stringify,
     deserialize: JSON.parse,
     partialize: (state) => state,
     version: 0,
-    merge: (persistedState, currentState) => __spreadValues(__spreadValues({}, currentState), persistedState)
+    merge: (persistedState, currentState) => __spreadValues(__spreadValues({}, currentState), typeof persistedState === "object" ? persistedState : {})
   }, baseOptions);
   let hasHydrated = false;
   const hydrationListeners = /* @__PURE__ */ new Set();
@@ -341,5 +306,15 @@
   hydrate();
   return stateFromStorage || configResult;
 };
+const persist = persistImpl;
+
+const immerImpl = (initializer) => (set, get, store) => {
+  store.setState = (updater, replace) => {
+    const nextState = typeof updater === "function" ? produce(updater) : updater;
+    return set(nextState, replace);
+  };
+  return initializer(store.setState, get, store);
+};
+const immer = immerImpl;
 
-export { combine, devtools, persist, redux, subscribeWithSelector };
+export { combine, devtools, immer, persist, redux, subscribeWithSelector };
diff -ur dist-v4/esm/vanilla.js dist/esm/vanilla.js
--- dist-v4/esm/vanilla.js	2022-04-05 15:48:43.000000000 +0900
+++ dist/esm/vanilla.js	2022-04-05 15:51:55.000000000 +0900
@@ -1,4 +1,4 @@
-function createStore(createState) {
+const createStoreImpl = (createState) => {
   let state;
   const listeners = /* @__PURE__ */ new Set();
   const setState = (partial, replace) => {
@@ -18,6 +18,7 @@
   const api = { setState, getState, subscribe, destroy };
   state = createState(setState, getState, api);
   return api;
-}
+};
+const createStore = (createState) => createState ? createStoreImpl(createState) : createStoreImpl;
 
 export { createStore as default };
```

</details>

Oops, I found a weird diff in context.js.

File: src/context.ts [hunk 46]
```diff
@@ -6,38 +6,31 @@ import {
...
   useRef,
 } from 'react'
-import {
-  EqualityChecker,
-  State,
-  StateSelector,
-  StoreApi,
-  useStore,
-} from 'zustand'
+import { EqualityChecker, State, StateSelector, StoreApi, useStore } from '.'
```
Comment (dai-shi) [inline src/context.ts:9]:
```suggestion
import { EqualityChecker, State, StateSelector, StoreApi, useStore } from 'zustand'
```
This is it.

**Review by dai-shi — CHANGES_REQUESTED** [review]

File: src/context.ts (hunk 46 above)
Comment (devanshj) [reply src/context.ts]: Good catch

**Comment by devanshj** [comment]
> @devanshj Would you check the diff of middleware/devtools.js and, if it's valid, list the changes in the PR description?

The diff looks fine but most of it shouldn't belong to this PR, so I opened #892. Once you merge it with v4, I'll update this branch and then the diff should be better.

**Comment by dai-shi** [comment]
Hi, v4 branch is updated (cherry-picked #892 commits). Please resolve conflicts.

**Comment by dai-shi** [comment]
<details>
<summary>diff -ur dist-v4/esm dist/esm (js only)</summary>

```diff
diff -urw dist-v4/esm/index.js dist/esm/index.js
--- dist-v4/esm/index.js	2022-04-07 10:42:20.000000000 +0900
+++ dist/esm/index.js	2022-04-07 10:43:16.000000000 +0900
@@ -1,7 +1,7 @@
 import { useDebugValue } from 'react';
 import { useSyncExternalStoreWithSelector } from 'use-sync-external-store/shim/with-selector.js';
 
-function createStore(createState) {
+const createStoreImpl = (createState) => {
   let state;
   const listeners = /* @__PURE__ */ new Set();
   const setState = (partial, replace) => {
@@ -21,18 +21,22 @@
   const api = { setState, getState, subscribe, destroy };
   state = createState(setState, getState, api);
   return api;
-}
+};
+const createStore = (createState) => createState ? createStoreImpl(createState) : createStoreImpl;
+var createStore$1 = createStore;
 
 function useStore(api, selector = api.getState, equalityFn) {
   const slice = useSyncExternalStoreWithSelector(api.subscribe, api.getState, api.getServerState || api.getState, selector, equalityFn);
   useDebugValue(slice);
   return slice;
 }
-function create(createState) {
-  const api = typeof createState === "function" ? createStore(createState) : createState;
+const createImpl = (createState) => {
+  const api = typeof createState === "function" ? createStore$1(createState) : createState;
   const useBoundStore = (selector, equalityFn) => useStore(api, selector, equalityFn);
   Object.assign(useBoundStore, api);
   return useBoundStore;
-}
+};
+const create = (createState) => createState ? createImpl(createState) : createImpl;
+var create$1 = create;
 
-export { create as default, useStore };
+export { create$1 as default, useStore };
diff -urw dist-v4/esm/middleware.js dist/esm/middleware.js
--- dist-v4/esm/middleware.js	2022-04-07 10:42:17.000000000 +0900
+++ dist/esm/middleware.js	2022-04-07 10:43:12.000000000 +0900
@@ -1,3 +1,5 @@
+import { produce } from 'immer';
+
 var __defProp$1 = Object.defineProperty;
 var __getOwnPropSymbols$1 = Object.getOwnPropertySymbols;
 var __hasOwnProp$1 = Object.prototype.hasOwnProperty;
@@ -14,7 +16,7 @@
     }
   return a;
 };
-const redux = (reducer, initial) => (set, get, api) => {
+const reduxImpl = (reducer, initial) => (set, get, api) => {
   api.dispatch = (action) => {
     set((state) => reducer(state, action), false, action);
     return action;
@@ -22,9 +24,9 @@
   api.dispatchFromDevtools = true;
   return __spreadValues$1({ dispatch: (...a) => api.dispatch(...a) }, initial);
 };
+const redux = reduxImpl;
 
-function devtools(fn, options) {
-  return (set, get, api) => {
+const devtoolsImpl = (fn, options) => (set, get, api) => {
     const devtoolsOptions = options === void 0 ? {} : typeof options === "string" ? { name: options } : options;
     let extensionConnector;
     try {
@@ -57,7 +59,7 @@
       let didWarnAboutReservedActionType = false;
       const originalDispatch = api.dispatch;
       api.dispatch = (...a) => {
-        if (a[0].type === "__setState" && !didWarnAboutReservedActionType) {
+      if ((import.meta.env && import.meta.env.MODE) !== "production" && a[0].type === "__setState" && !didWarnAboutReservedActionType) {
           console.warn('[zustand devtools middleware] "__setState" action type is reserved to set state from the devtools. Avoid using it.');
           didWarnAboutReservedActionType = true;
         }
@@ -117,7 +119,7 @@
     });
     return initialState;
   };
-}
+const devtools = devtoolsImpl;
 const parseJsonThen = (stringified, f) => {
   let parsed;
   try {
@@ -129,7 +131,7 @@
     f(parsed);
 };
 
-const subscribeWithSelector = (fn) => (set, get, api) => {
+const subscribeWithSelectorImpl = (fn) => (set, get, api) => {
   const origSubscribe = api.subscribe;
   api.subscribe = (selector, optListener, options) => {
     let listener = selector;
@@ -152,8 +154,9 @@
   const initialState = fn(set, get, api);
   return initialState;
 };
+const subscribeWithSelector = subscribeWithSelectorImpl;
 
-const combine = (initialState, create) => (set, get, api) => Object.assign({}, initialState, create(set, get, api));
+const combine = (initialState, create) => (...a) => Object.assign({}, initialState, create(...a));
 
 var __defProp = Object.defineProperty;
 var __getOwnPropSymbols = Object.getOwnPropertySymbols;
@@ -196,14 +199,14 @@
     };
   }
 };
-const persist = (config, baseOptions) => (set, get, api) => {
+const persistImpl = (config, baseOptions) => (set, get, api) => {
   let options = __spreadValues({
     getStorage: () => localStorage,
     serialize: JSON.stringify,
     deserialize: JSON.parse,
     partialize: (state) => state,
     version: 0,
-    merge: (persistedState, currentState) => __spreadValues(__spreadValues({}, currentState), persistedState)
+    merge: (persistedState, currentState) => __spreadValues(__spreadValues({}, currentState), typeof persistedState === "object" ? persistedState : {})
   }, baseOptions);
   let hasHydrated = false;
   const hydrationListeners = /* @__PURE__ */ new Set();
@@ -303,5 +306,15 @@
   hydrate();
   return stateFromStorage || configResult;
 };
+const persist = persistImpl;
+
+const immerImpl = (initializer) => (set, get, store) => {
+  store.setState = (updater, replace) => {
+    const nextState = typeof updater === "function" ? produce(updater) : updater;
+    return set(nextState, replace);
+  };
+  return initializer(store.setState, get, store);
+};
+const immer = immerImpl;
 
-export { combine, devtools, persist, redux, subscribeWithSelector };
+export { combine, devtools, immer, persist, redux, subscribeWithSelector };
diff -urw dist-v4/esm/vanilla.js dist/esm/vanilla.js
--- dist-v4/esm/vanilla.js	2022-04-07 10:42:15.000000000 +0900
+++ dist/esm/vanilla.js	2022-04-07 10:43:11.000000000 +0900
@@ -1,4 +1,4 @@
-function createStore(createState) {
+const createStoreImpl = (createState) => {
   let state;
   const listeners = /* @__PURE__ */ new Set();
   const setState = (partial, replace) => {
@@ -18,6 +18,7 @@
   const api = { setState, getState, subscribe, destroy };
   state = createState(setState, getState, api);
   return api;
-}
+};
+const createStore = (createState) => createState ? createStoreImpl(createState) : createStoreImpl;
 
 export { createStore as default };
```

</details>

Looks much cleaner.

**Review by dai-shi — COMMENTED** [review]
The code looks good.
I will merge other v4 PRs into the main branch soon.
What's remaining on your end for this PR?

File: src/middleware/persist.ts [hunk 47]
```diff
@@ -144,188 +124,207 @@ const toThenable =
...
+  type S = ReturnType<typeof config>
+  let options = {
+    getStorage: () => localStorage,
+    serialize: JSON.stringify as (state: StorageValue<S>) => string,
+    deserialize: JSON.parse as (str: string) => StorageValue<S>,
+    partialize: (state: S) => state,
+    version: 0,
+    merge: (persistedState: unknown, currentState: S) => ({
+      ...currentState,
+      ...(typeof persistedState === 'object' ? persistedState : {}),
```
[the remark this answers is not in the document]
Comment (devanshj) [reply src/middleware/persist.ts:137]: `persistedState` comes from the (local)storage so it can be anything (hence it's `unknown`), for eg  it could even be a number, technically `{ ...3 }` doesn't throw but typescript doesn't allow spreading non-objects hence the change.

**Comment by devanshj** [comment]
> What's remaining on your end for this PR?

Adding a recipe for the slices pattern in the typescript md

File: src/middleware/persist.ts (hunk 47 above)
[the remark this answers is not in the document]
Comment (devanshj) [reply src/middleware/persist.ts:137]: Yes it's kinda a TS issue. TS is conservative when it comes to spreading so that you don't accidentally spread a non-object (as most likely it'd be a mistake because it's not semantically correct). But for our case this acts like a false positive, so we can do `{ ...(persistedState as object) }` (or even `any` for that matter). Would you prefer that? Idm eitherway.

(I did the object check because I also consider spreading non-objects semantically wrong even if js doesn't throw)

File: readme.md [hunk 48]
```diff
@@ -581,48 +527,32 @@ const Component = () => {
...
-import { combine } from 'zustand/middleware'
-
-const useStore = create(
-  combine(
-    { bears: 0 },
-    (set) => ({ increase: (by: number) => set((state) => ({ bears: state.bears + by })) })
-  ),
-)
-```
+A more complete TypeScript guide is [here](https://github.com/pmndrs/zustand/blob/main/docs/typescript.md).
```
Comment (dai-shi) [inline readme.md:554]: Can we make it relative?
```suggestion
A more complete TypeScript guide is [here](./docs/typescript.md).
```

File: docs/typescript.md [hunk 49]
```diff
@@ -0,0 +1,315 @@
...
+import create from "zustand"
+import { combine } from "zustand/middleware"
+
+const useStore = create(combine({ bears: 0 }, (set) => ({
+  increase: (by: number) => set((state) => ({ bears: state.bears + by })),
+}))
+```
+
+<details>
+  <summary>But there's a little cost...</summary>
```
Comment (dai-shi) [inline docs/typescript.md:119]: I wouldn't call it "cost". Maybe "remark"?

File: docs/typescript.md [hunk 50]
```diff
@@ -0,0 +1,315 @@
...
+import create, { State, StateCreator, StoreMutatorIdentifier, Mutate, StoreApi } from "zustand"
+
+interface BearState {
+  bears: number
+  increase: (by: number) => void
+}
+
+const useStore = create<
+  BearState,
+  [],
```
Comment (dai-shi) [inline docs/typescript.md:306]: Reading types in `react.ts` again, don't we only have two type arguments?

File: docs/v4-migration.md [hunk 51]
```diff
@@ -0,0 +1,205 @@
+# v4 Migrations
+
+If you're not using the typed version (either via TypeScript or via JSDoc) then there are no breaking changes for you and hence no migration is needed either.
+
+Also it's recommended to first read the new [TypeScript Guide](https://github.com/pmndrs/zustand/blob/main/docs/typescript.md), it'll be easier to understand the migration.
+
+In addition to this migration guide you can also check the diff of the test files in the repo from v3 to v4.
+
+## `create` (from `zustand`, `zustand/vanilla`, and `zustand/react`)
```
Comment (dai-shi) [inline docs/v4-migration.md:9]: We don't have `zustand/react` as exported entry, so:
```suggestion
## `create` (from `zustand` and `zustand/vanilla`)
```

File: docs/v4-migration.md [hunk 52]
```diff
@@ -0,0 +1,205 @@
...
+- create:
+-   < State
+-   , StoreSetState = StoreApi<State>["set"]
+-   , StoreGetState = StoreApi<State>["get"]
+-   , Store = StoreApi<State>
+-   >
+-     (f: ...) => ...
++ create:
++   { <State>(): (f: ...) => ...
++   , <State, InMutators, OutMutators>(f: ...) => ...
```
Comment (dai-shi) [inline docs/v4-migration.md:23]: Again, it doesn't seem we have `InMutators` exposed here.

**Review by dai-shi — CHANGES_REQUESTED** [review]
Reviewed markdown files. Do we add docs about the immer middleware in this PR?

File: readme.md (hunk 48 above)
Comment (devanshj) [reply readme.md:554]: I'm not sure if it'll work, probably it won't.

File: docs/typescript.md (hunk 49 above)
Comment (devanshj) [reply docs/typescript.md:119]: How about "But there's a tradeoff"?

File: docs/typescript.md (hunk 50 above)
Comment (devanshj) [reply docs/typescript.md:306]: Ah right

File: readme.md (hunk 48 above)
Comment (dai-shi) [reply readme.md:554]: I'm sure it works in github, but not in npmjs.
It was "Not Found" for me when browsing the commit instead of `main`.

File: docs/typescript.md (hunk 49 above)
Comment (dai-shi) [reply docs/typescript.md]: That still sounds too negative to me. The downside is too little compared to the benefit.

**Comment by dai-shi** [comment]
Please change the base branch to `main`. Be most careful when resolving.

File: docs/typescript.md (hunk 49 above)
Comment (devanshj) [reply docs/typescript.md]: Fair enough hence I made it "But be a little careful..." is that better? If you want we can make it even less negative by removing the "but" — "Just be a little careful..."

**Comment by devanshj** [comment]
There's one persist test failing not sure why

File: docs/typescript.md (hunk 49 above)
Comment (dai-shi) [reply docs/typescript.md]: > "Just be a little careful..."

Let's do this.

**Comment by dai-shi** [comment]
<details>
<summary>diff -urw dist-943af08/esm dist-ee512ec/esm</summary>

```diff
diff -urw dist-943af08/esm/index.js dist-ee512ec/esm/index.js
--- dist-943af08/esm/index.js	2022-04-09 08:04:30.000000000 +0900
+++ dist-ee512ec/esm/index.js	2022-04-09 08:04:00.000000000 +0900
@@ -1,7 +1,7 @@
 import { useDebugValue } from 'react';
 import { useSyncExternalStoreWithSelector } from 'use-sync-external-store/shim/with-selector.js';
 
-function createStore(createState) {
+const createStoreImpl = (createState) => {
   let state;
   const listeners = /* @__PURE__ */ new Set();
   const setState = (partial, replace) => {
@@ -21,18 +21,22 @@
   const api = { setState, getState, subscribe, destroy };
   state = createState(setState, getState, api);
   return api;
-}
+};
+const createStore = (createState) => createState ? createStoreImpl(createState) : createStoreImpl;
+var createStore$1 = createStore;
 
 function useStore(api, selector = api.getState, equalityFn) {
   const slice = useSyncExternalStoreWithSelector(api.subscribe, api.getState, api.getServerState || api.getState, selector, equalityFn);
   useDebugValue(slice);
   return slice;
 }
-function create(createState) {
-  const api = typeof createState === "function" ? createStore(createState) : createState;
+const createImpl = (createState) => {
+  const api = typeof createState === "function" ? createStore$1(createState) : createState;
   const useBoundStore = (selector, equalityFn) => useStore(api, selector, equalityFn);
   Object.assign(useBoundStore, api);
   return useBoundStore;
-}
+};
+const create = (createState) => createState ? createImpl(createState) : createImpl;
+var create$1 = create;
 
-export { create as default, useStore };
+export { create$1 as default, useStore };
diff -urw dist-943af08/esm/middleware.js dist-ee512ec/esm/middleware.js
--- dist-943af08/esm/middleware.js	2022-04-09 08:04:26.000000000 +0900
+++ dist-ee512ec/esm/middleware.js	2022-04-09 08:03:56.000000000 +0900
@@ -1,3 +1,5 @@
+import { produce } from 'immer';
+
 var __defProp$1 = Object.defineProperty;
 var __getOwnPropSymbols$1 = Object.getOwnPropertySymbols;
 var __hasOwnProp$1 = Object.prototype.hasOwnProperty;
@@ -14,7 +16,7 @@
     }
   return a;
 };
-const redux = (reducer, initial) => (set, get, api) => {
+const reduxImpl = (reducer, initial) => (set, get, api) => {
   api.dispatch = (action) => {
     set((state) => reducer(state, action), false, action);
     return action;
@@ -22,9 +24,9 @@
   api.dispatchFromDevtools = true;
   return __spreadValues$1({ dispatch: (...a) => api.dispatch(...a) }, initial);
 };
+const redux = reduxImpl;
 
-function devtools(fn, options) {
-  return (set, get, api) => {
+const devtoolsImpl = (fn, options) => (set, get, api) => {
     const devtoolsOptions = options === void 0 ? {} : typeof options === "string" ? { name: options } : options;
     let extensionConnector;
     try {
@@ -117,7 +119,7 @@
     });
     return initialState;
   };
-}
+const devtools = devtoolsImpl;
 const parseJsonThen = (stringified, f) => {
   let parsed;
   try {
@@ -129,7 +131,7 @@
     f(parsed);
 };
 
-const subscribeWithSelector = (fn) => (set, get, api) => {
+const subscribeWithSelectorImpl = (fn) => (set, get, api) => {
   const origSubscribe = api.subscribe;
   api.subscribe = (selector, optListener, options) => {
     let listener = selector;
@@ -152,8 +154,9 @@
   const initialState = fn(set, get, api);
   return initialState;
 };
+const subscribeWithSelector = subscribeWithSelectorImpl;
 
-const combine = (initialState, create) => (set, get, api) => Object.assign({}, initialState, create(set, get, api));
+const combine = (initialState, create) => (...a) => Object.assign({}, initialState, create(...a));
 
 var __defProp = Object.defineProperty;
 var __getOwnPropSymbols = Object.getOwnPropertySymbols;
@@ -196,7 +199,7 @@
     };
   }
 };
-const persist = (config, baseOptions) => (set, get, api) => {
+const persistImpl = (config, baseOptions) => (set, get, api) => {
   let options = __spreadValues({
     getStorage: () => localStorage,
     serialize: JSON.stringify,
@@ -264,8 +267,7 @@
         }
       }
     }).then((migratedState) => {
-      var _a2;
-      stateFromStorage = options.merge(migratedState, (_a2 = get()) != null ? _a2 : configResult);
+      stateFromStorage = options.merge(migratedState, configResult);
       set(stateFromStorage, true);
       return setItem();
     }).then(() => {
@@ -304,5 +306,15 @@
   hydrate();
   return stateFromStorage || configResult;
 };
+const persist = persistImpl;
+
+const immerImpl = (initializer) => (set, get, store) => {
+  store.setState = (updater, replace) => {
+    const nextState = typeof updater === "function" ? produce(updater) : updater;
+    return set(nextState, replace);
+  };
+  return initializer(store.setState, get, store);
+};
+const immer = immerImpl;
 
-export { combine, devtools, persist, redux, subscribeWithSelector };
+export { combine, devtools, immer, persist, redux, subscribeWithSelector };
diff -urw dist-943af08/esm/vanilla.js dist-ee512ec/esm/vanilla.js
--- dist-943af08/esm/vanilla.js	2022-04-09 08:04:25.000000000 +0900
+++ dist-ee512ec/esm/vanilla.js	2022-04-09 08:03:54.000000000 +0900
@@ -1,4 +1,4 @@
-function createStore(createState) {
+const createStoreImpl = (createState) => {
   let state;
   const listeners = /* @__PURE__ */ new Set();
   const setState = (partial, replace) => {
@@ -18,6 +18,7 @@
   const api = { setState, getState, subscribe, destroy };
   state = createState(setState, getState, api);
   return api;
-}
+};
+const createStore = (createState) => createState ? createStoreImpl(createState) : createStoreImpl;
 
 export { createStore as default };
```

</details>

> There's one persist test failing not sure why

You seem to fail merging the change in #894.

File: src/react.ts [hunk 53]
```diff
@@ -2,18 +2,17 @@ import { useDebugValue } from 'react'
...
 
-export function useStore<T extends State>(api: StoreApi<T>): T
-export function useStore<T extends State, U>(
-  api: StoreApi<T>,
-  selector: StateSelector<T, U>,
+export function useStore<S extends StoreApi<State>, U = ExtractState<S>>(
+  api: S,
+  selector?: StateSelector<ExtractState<S>, U>,
   equalityFn?: EqualityChecker<U>
 ): U
```
Comment (dai-shi) [inline src/react.ts:17]: We should prefer function overloading here too, as we discussed in [#812](https://github.com/pmndrs/zustand/issues/812#issuecomment-1046324462), no?

File: src/middleware/immer.ts [hunk 54]
```diff
@@ -0,0 +1,66 @@
+import { produce } from 'immer'
+import type { Draft } from 'immer'
```
Comment (dai-shi) [inline src/middleware/immer.ts:2]: We don't emit `import type` assuming old TS doesn't support it.
```suggestion
import { Draft, produce } from 'immer'
```

File: src/react.ts (hunk 53 above)
Comment (devanshj) [reply src/react.ts:17]: Ah right

File: src/middleware/immer.ts (hunk 54 above)
Comment (devanshj) [reply src/middleware/immer.ts:2]: But then `eslint(import/named)` complains because it doesn't understand `Draft` is a type. As I had probably said before TypeScript projects don't even need `eslint(import/named)`. So should I remove the lint rule?

Comment (dai-shi) [reply src/middleware/immer.ts:2]: Oh, I wasn't aware that. (Why doesn't eslint understand the `Draft` type??)
We maintain the same eslintrc json file among zustand/jotai/valtio, so for this PR, please just add `// eslint-disable-next-line import/named`.

Comment (devanshj) [reply src/middleware/immer.ts:2]: > Why doesn't eslint understand the Draft type??

Not sure, perhaps eslint doesn't check `.d.ts`, or it could even be a bug

> please just add // eslint-disable-next-line import/named.

Sure

**Comment by dai-shi** [comment]
<details>
<summary>diff -urw dist-943af08/esm dist-160f11d/esm</summary>

```diff 
diff -urw dist-943af08/esm/index.js dist-160f11d/esm/index.js
--- dist-943af08/esm/index.js	2022-04-09 08:04:30.000000000 +0900
+++ dist-160f11d/esm/index.js	2022-04-10 09:15:04.000000000 +0900
@@ -1,7 +1,7 @@
 import { useDebugValue } from 'react';
 import { useSyncExternalStoreWithSelector } from 'use-sync-external-store/shim/with-selector.js';
 
-function createStore(createState) {
+const createStoreImpl = (createState) => {
   let state;
   const listeners = /* @__PURE__ */ new Set();
   const setState = (partial, replace) => {
@@ -21,18 +21,22 @@
   const api = { setState, getState, subscribe, destroy };
   state = createState(setState, getState, api);
   return api;
-}
+};
+const createStore = (createState) => createState ? createStoreImpl(createState) : createStoreImpl;
+var createStore$1 = createStore;
 
 function useStore(api, selector = api.getState, equalityFn) {
   const slice = useSyncExternalStoreWithSelector(api.subscribe, api.getState, api.getServerState || api.getState, selector, equalityFn);
   useDebugValue(slice);
   return slice;
 }
-function create(createState) {
-  const api = typeof createState === "function" ? createStore(createState) : createState;
+const createImpl = (createState) => {
+  const api = typeof createState === "function" ? createStore$1(createState) : createState;
   const useBoundStore = (selector, equalityFn) => useStore(api, selector, equalityFn);
   Object.assign(useBoundStore, api);
   return useBoundStore;
-}
+};
+const create = (createState) => createState ? createImpl(createState) : createImpl;
+var create$1 = create;
 
-export { create as default, useStore };
+export { create$1 as default, useStore };
diff -urw dist-943af08/esm/middleware.js dist-160f11d/esm/middleware.js
--- dist-943af08/esm/middleware.js	2022-04-09 08:04:26.000000000 +0900
+++ dist-160f11d/esm/middleware.js	2022-04-10 09:15:01.000000000 +0900
@@ -1,3 +1,5 @@
+import { produce } from 'immer';
+
 var __defProp$1 = Object.defineProperty;
 var __getOwnPropSymbols$1 = Object.getOwnPropertySymbols;
 var __hasOwnProp$1 = Object.prototype.hasOwnProperty;
@@ -14,7 +16,7 @@
     }
   return a;
 };
-const redux = (reducer, initial) => (set, get, api) => {
+const reduxImpl = (reducer, initial) => (set, get, api) => {
   api.dispatch = (action) => {
     set((state) => reducer(state, action), false, action);
     return action;
@@ -22,9 +24,9 @@
   api.dispatchFromDevtools = true;
   return __spreadValues$1({ dispatch: (...a) => api.dispatch(...a) }, initial);
 };
+const redux = reduxImpl;
 
-function devtools(fn, options) {
-  return (set, get, api) => {
+const devtoolsImpl = (fn, options) => (set, get, api) => {
     const devtoolsOptions = options === void 0 ? {} : typeof options === "string" ? { name: options } : options;
     let extensionConnector;
     try {
@@ -117,7 +119,7 @@
     });
     return initialState;
   };
-}
+const devtools = devtoolsImpl;
 const parseJsonThen = (stringified, f) => {
   let parsed;
   try {
@@ -129,7 +131,7 @@
     f(parsed);
 };
 
-const subscribeWithSelector = (fn) => (set, get, api) => {
+const subscribeWithSelectorImpl = (fn) => (set, get, api) => {
   const origSubscribe = api.subscribe;
   api.subscribe = (selector, optListener, options) => {
     let listener = selector;
@@ -152,8 +154,9 @@
   const initialState = fn(set, get, api);
   return initialState;
 };
+const subscribeWithSelector = subscribeWithSelectorImpl;
 
-const combine = (initialState, create) => (set, get, api) => Object.assign({}, initialState, create(set, get, api));
+const combine = (initialState, create) => (...a) => Object.assign({}, initialState, create(...a));
 
 var __defProp = Object.defineProperty;
 var __getOwnPropSymbols = Object.getOwnPropertySymbols;
@@ -196,7 +199,7 @@
     };
   }
 };
-const persist = (config, baseOptions) => (set, get, api) => {
+const persistImpl = (config, baseOptions) => (set, get, api) => {
   let options = __spreadValues({
     getStorage: () => localStorage,
     serialize: JSON.stringify,
@@ -304,5 +307,15 @@
   hydrate();
   return stateFromStorage || configResult;
 };
+const persist = persistImpl;
+
+const immerImpl = (initializer) => (set, get, store) => {
+  store.setState = (updater, replace) => {
+    const nextState = typeof updater === "function" ? produce(updater) : updater;
+    return set(nextState, replace);
+  };
+  return initializer(store.setState, get, store);
+};
+const immer = immerImpl;
 
-export { combine, devtools, persist, redux, subscribeWithSelector };
+export { combine, devtools, immer, persist, redux, subscribeWithSelector };
diff -urw dist-943af08/esm/vanilla.js dist-160f11d/esm/vanilla.js
--- dist-943af08/esm/vanilla.js	2022-04-09 08:04:25.000000000 +0900
+++ dist-160f11d/esm/vanilla.js	2022-04-10 09:15:00.000000000 +0900
@@ -1,4 +1,4 @@
-function createStore(createState) {
+const createStoreImpl = (createState) => {
   let state;
   const listeners = /* @__PURE__ */ new Set();
   const setState = (partial, replace) => {
@@ -18,6 +18,7 @@
   const api = { setState, getState, subscribe, destroy };
   state = createState(setState, getState, api);
   return api;
-}
+};
+const createStore = (createState) => createState ? createStoreImpl(createState) : createStoreImpl;
 
 export { createStore as default };
```

</details>

Looks perfect!

**Comment by dai-shi** [comment]
One remaining issue to be resolved: https://github.com/pmndrs/zustand/pull/725#discussion_r846546318

Anything else?

File: src/react.ts [hunk 55]
```diff
@@ -2,20 +2,25 @@ import { useDebugValue } from 'react'
...
+export function useStore<S extends StoreApi<State>>(api: S): ExtractState<S>
+export function useStore<S extends StoreApi<State>, U>(
+  api: S,
+  selector: StateSelector<ExtractState<S>, U>,
   equalityFn?: EqualityChecker<U>
 ): U
+export function useStore<S extends StoreApi<State>>(
+  api: S,
+  selector: undefined,
+  equalityFn?: EqualityChecker<ExtractState<S>>
```
Comment (dai-shi) [inline src/react.ts:22]: Do we need `?` for `equalityFn`? Maybe, you want to be precise.
What do you think about adding JSDoc saying "this is supported for edge cases, but generally not recommended"?

**Review by dai-shi — APPROVED** [review]
The rest seems good to me.

File: src/react.ts (hunk 55 above)
Comment (devanshj) [reply src/react.ts:22]: > Do we need `?` for `equalityFn`? Maybe, you want to be precise. That's fair.

Yeah exactly to be precise, as `useStore(undefined, undefined)` should also compile (I too thought about this but then came to conclusion this is how it should be)

> What do you think about adding JSDoc saying "this is supported for edge cases, but generally not recommended"?

I don't really follow why it would be an edge case to require something `useStore(undefined, shallowEq)`. But if you think that users should be cautious then there's no harm in adding a JSDoc. Also if you think it'd be better to remove this overload then I'm open to that too, given you know better.

**Comment by devanshj** [comment]
> Anything else?

There are a few small type tweaks pending, I'll continue tomorrow.

File: src/react.ts (hunk 55 above)
Comment (dai-shi) [reply src/react.ts:22]: To me, it's important to have types for good docs and it doesn't have to be precise about the JS implementation. (TS users can always use type assertion if they want.)
If I were a user, I would read all three overloaded types to understand the entire API, but for almost all cases, the first two are enough. I don't see the need for the third one, because it's almost always a bad practice to use equalityFn for the entire state object. (It's a hacky optimization which can behave inconsistently.) So, it's an extra mental overhead.

If adding JSDoc works (if it shows in editors), let's do it. Otherwise, let's remove.
```js
/**
 * Caution: Although this signature is supported, it's not generally a good practice to depend on equalityFn for the entire state.
 */
```
Does JSDoc work for `useBoundStore` and `UseContextStore` too?


> require something like `useStore(undefined, shallowEq)`

We would never need this. For 99.9% of use cases, the behavior is the same as `useStore()`. Put it in another way, `equalityFn` is **designed** to be used when `selector` is specified. If I see using `equalityFn` without `selector`, I suspect it's a mis-usage for 99% of use cases.

> should also compile

Maybe, we are coming from the different world. Mine is more or less "what TS compiles should work in JS".

Comment (devanshj) [reply src/react.ts:22]: > For 99.9% of use cases, the behavior is the same as useStore().

Ah right, rethinking about it this and it's true that `useStore(undefined, someEquality)` is going to be same as `useStore()` (unless users are doing some nasty mutations eg `get().foo.bar = 41` or whatever which is obviously not valid usage).

Okay so this changes my entire perspective, I was under impression that selector and equality are more or less orthogonal and the type is `(selector?: ..., equals?: ...) => ...` (much like `(options: { selector?: ..., equals?: ... }) => ...`) but it seems to be the type is `{ (): ..., (selector: ..., equals?: ...): ... }` ie custom equality truly only makes sense in presence of a selector.

So yeah let's remove this overload.

**Comment by devanshj** [comment]
Okay so let me explain the recent commits a bit...

> f0d192a make immer more generic

This one is fairly simple, we're making less assumptions about the the "parent" `setState` so now we're forwarding the 2-n arguments. So for example previously `create(immer(devtools(() => ...))` would have not worked but now it'd work. 

The `SkipTwo` type is rather complex because a basic one like this...
```ts
type SkipTwoBasic<T> =
  T extends [] ? [] :
  T extends [unknown] ? [] :
  T extends [unknown, unknown, ...infer A] ? A :
  never
```
... won't work because the way subtyping works ie `["a"?] extends [unknown] ? true : false` is actually `false` instead of true. So `SkipTwoBasic<[{ count: number }, boolean?, string?]>` would return `never` instead of `[string?]`. So the actual `SkipTwo` that's committed gives `[string?]`.

> 58dc684 make devtools replace-friendly and more correctly typed

I don't know if you remember but this PR actually bring a new feature that whenever users are replacing the state, they'll have to pass the whole state, so now we have more type safety. I also added a test for this: https://github.com/pmndrs/zustand/pull/725/commits/061a057e8f050b596d167afbd23c806645258229.

But the problem is this feature only work if there are no higher kinded mutators that change `setState` and `devtools` does that...

```ts
declare module '../vanilla' {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  interface StoreMutators<S, A> {
    'zustand/devtools': WithDevtools<S>
  }
}

type WithDevtools<S> =
  Write<Cast<S, object>, StoreSetStateWithAction<S>>

type StoreSetStateWithAction<S> =
  S extends { setState: (...a: infer A) => infer R }
    ? { setState: (...a: [...a: A, actionType?: string | { type: unknown }]) => R }
    : never

type Write<T extends object, U extends object> = Omit<T, keyof U> & U
type Cast<T, U> = T extends U ? T : U
```

Here the problem is that when you use `infer` to extract the arguments, it looses all type parameters (ie `Nt` and `R` on `setState` which make the replace feature work) so hence this replace feature wouldn't work if someone is using devtools middleware.

Unfortunately this is a TypeScript limitation, and there's no workaround to this. Hence what we do now is add special cases for the type of setStates we know, ie vanilla and immer. So now `StoreSetStateWithAction` would look like this...

```ts
type StoreSetStateWithAction<S> =
  S extends { getState: () => infer T, setState: (...a: infer A) => infer R }
    ? A extends [Partial<T> | ((state: T) => Partial<T>), (boolean | undefined)?]
        ? /* redefining vanilla setState but now with `actionType` */ :
      A extends [Partial<T> | ((state: Draft<T>) => void), (boolean | undefined)?]
        ? /* redefining immer setState but now with `actionType` */ :
      { setState: (...a: [...a: A, actionType?: string | { type: unknown }]) => R }
      // fallback, this would lose replace-aware feature
    : never
```

And now the replace feature would work even for devtools (with vanilla or immer). You can see I've added those tests for it in `types.test.ts` in below to the vanilla replace test.

Additionally, `[...a: A, actionType?: string | { type: unknown }]` is actually wrong because `A` can have more than two elements so now we do  `[...a: TakeTwo<A>, actionType?: string | { type: unknown }]`.

> 374a5f0 migrate tests

Ha we caught some bugs in the tests because of this additionally type safety. Previously as I said devtools wouldn't have the replace feature but now it does, so we caught passing partial state when we were replacing.

> 3063df1 make setState bivariant to make the state covariant

Okay now this one is a bit lengthy. And it's time to sleep so I'll explain tomorrow xD

I know the types have gotten a bit more complex but I think it's worth it, we've already come this far so a little more correctness is doesn't harm.

File: src/react.ts (hunk 55 above)
Comment (dai-shi) [reply src/react.ts]: > So yeah let's remove this overload.

👍 

> is almost a coincidental unintended by-product

true. well described.

> we don't do that because it'll affect the bundle size etc.

right. and so far I don't see many people misunderstand it.

**Comment by dai-shi** [comment]
> I understand I'm being a perfectionist here, but that's who I am :P

well, I know, but keep in mind that if you make things too complicated and others can't follow, we will eventually remove that code in the future abandoning your work and effort. Non-understandable code is worse than non-perfect code. So, you should find the balance between perfectness and understandability. tbh, you already went too far.

> The SkipTwo type is rather complex because a basic one like this

SkipTwo is complex, but understandable because the goal is clear.

> may have some middleware which has a special setState that returns something

I actually like it. > `return r`

> Unfortunately this is a TypeScript limitation, and there's no workaround to this. Hence what we do now is add special cases for the types of setStates that we know of, ie vanilla and immer.

Can we give this up, and make things less complicated? Using `replace` is not a very common case, so putting more effort and making things complex don't give much benefit overall. I'd like to keep this limitation if there's a solution with manual typing (no type inference).

**Comment by devanshj** [comment]
I understand what you're getting at, but I don't think correctness of code and understandability of code are always mutually exclusive. It depends, here the assumption is the maintainers have medium-to-high typescript knowledge (and have my detailed documentations) and the type-level code requires zero maintenance (apart from future bugs which are unlikely and I'll mostly be available), so we can have both. Of course if these conditions are not met then it's perfectly reasonable to delete my code, I don't mind that nor do I think my work goes in vain.

> Can we give this up, and make things less complicated? Using replace is not a very common case, so putting more effort and making things complex don't give much benefit overall. I'd like to keep this limitation if there's a solution with manual typing (no type inference).

Keeping the limitation would not reduce the complexity by any significant margin, it'll only remove the two added branches (ie vanilla and immer) in `StoreSetStateWithAction`, that's it. I don't think it makes sense to come so far (with things like #710) and not go an inch more.

The alternative is that users will have to be careful themselves and pass the whole state when replacing, the compiler won't help them. I'd suggest not to compromise, but you can take the final call.

**Comment by dai-shi** [comment]
> here the assumption is the maintainers have medium-to-high typescript knowledge (and have my detailed documentations)

You are too optimistic about this. The maintainers skills are not high enough as you expect to modify those code (and understand your detailed documents). Moreover, other contributors/users can't read the code. How would they become confident with the code they don't understand? It's like a different programming language for someone.

> it'll only remove the two added branches (ie vanilla and immer) in StoreSetStateWithAction, that's it.

I know, and this means if someone creates a new middleware at their own, the type inference will break, right? Creating own middleware and using `replace` are both rare, though.

---

I don't have any solution. Just feels like it's too complicated, and if you have any idea to compromise, it's worth considering.

**Comment by dai-shi** [comment]
> 3063df1 make setState bivariant to make the state covariant

I don't fully understand invariant/covariant things, but the commit is readable. If there are tests to cover, I could follow it.

**Comment by devanshj** [comment]
> if someone creates a new middleware at their own, the type inference will break, right?

No, here's the scenario..

- **If** user creates a middleware (let's call it `myMiddleware`)...
- ...**and** the they mutate `setState` in it (like `devtools` and `immer` do)...
- ...**and** they use it with `devtools`...
- ...**and** they write `myMiddleware(devtools(...` instead of `devtools(myMiddleware(...`
- ...**and** they pass replace as `true`...
- ...**and** they forget to pass the whole state...
- ...**then** it'll still compile...
- ...**instead of** not compiling.

So it won't break anything, the type inference will still work, everything will be the same, just the types will become less strict.

Let me clarify the typescript limitation a bit...

```ts
type State = { count: number }

declare const setState:
  <R extends boolean | undefined>
    ( partial: R extends true ? State : Partial<State>
    , replace?: R
    ) =>
      void

setState({}, true)
// doesn't compile, great, it's strict and prevents runtime exceptions

declare const withDevtools:
  <F extends (...a: never[]) => unknown>
    (f: F) =>
      // code same as the fallback branch in `StoreSetStateWithAction`
      F extends (...a: infer A) => infer R
        ? (...a: [...a0: TakeTwo<A>, name?: string]) => R
        : never
    
type TakeTwo<T> =
  T extends [] ? [undefined, undefined] :
  T extends [unknown] ? [...a0: T, a1: undefined] :
  T extends [unknown?] ? [...a0: T, a1: undefined] :
  T extends [unknown, unknown] ? T :
  T extends [unknown, unknown?] ? T :
  T extends [unknown?, unknown?] ? T :
  T extends [infer A0, infer A1, ...unknown[]] ? [A0, A1] :
  T extends [infer A0, (infer A1)?, ...unknown[]] ? [A0, A1?] :
  T extends [(infer A0)?, (infer A1)?, ...unknown[]] ? [A0?, A1?] :
  never

const setStateWithDevtools = withDevtools(setState)
// all we wanted to do is add an argument at 2nd index
// we did that but now we also lost all generics
// (hover over `setStateWithDevtools`)

setStateWithDevtools({}, true)
// compiles, not that great as it's not strict and doesn't prevent runtime exceptions
```

---

> You are too optimistic about this. The maintainers skills are not high enough as you expect to modify those code (and understand your detailed documents). Moreover, other contributors/users can't read the code. How would they become confident with the code they don't understand? It's like a different programming language for someone.

> I don't have any solution. Just feels like it's too complicated, and if you have any idea to compromise, it's worth considering.

I just want to make sure you realize there's no pressure from my side, only suggestions. To quote from #662's description...

> You can keep as much code as you want.

My job is to offer you the most correct code possible. Your job is keep whatever code you like, which means I tailor the code according to your needs. I can at best suggest you, the decision will be yours.

So here given you find `StoreSetStateWithAction` complicated (I guess that's what you're referring to) then I can make it less complicated for you, the price is you'll have to give up the strict replace feature.

I just committed "fb624ac remove strict replace" you can check the change in code and tests.

You have two options here:
- Keep this commit
- Revert this commit

The first option takes away the strict replace feature for making the code less complicated. The second option makes the code more complicated for the strict replace feature.

My suggestion is still this...

> Keeping the limitation would not reduce the complexity by any significant margin, it'll only remove the two added branches (ie vanilla and immer) in `StoreSetStateWithAction`, that's it. I don't think it makes sense to come so far (with things like https://github.com/pmndrs/zustand/issues/710) and not go an inch more.

...and it's only a suggestion, really. You should do what is right according to you, because everyone has different OSS philosophies, different judgements of the risk-to-reward ratio, different responsibilities, etc. Any my apologies if my suggestions came across as some kind of pressure to accept them.

Also if the code is still complicated for you (given you tell me which part) then I can still make more compromises and make it less complicated, feel free to tell me.

**Comment by dai-shi** [comment]
> ...then it'll still compile...
> ...instead of not compiling.

I see. Yeah, this applies to `replace`. (Technically, `setState` can be mutated to break compiling?)

> ...and they write myMiddleware(devtools(... instead of devtools(myMiddleware(...

I missed this part. We can suggest using devtools at leaf level.

> So here given you find StoreSetStateWithAction complicated (I guess that's what you're referring to)

It was the start of this discussion, but in general, it's too complicated to be too good.

> Also if the code is still complicated for you (given you tell me which part)

I'll see the code again. But, probably more I read, more I get how it works, and "wow, it's good".

> You have two options here:

From the lib maintaining perspective, adding feature (including strict checks) is easier than removing it. So, I will keep fb624ac commit in this PR. Alternatively, as having an option is good, I will open a new PR for adding "strict replace" and I will consider merging after releasing v4 and getting more feedback. Or, maybe you want to open the PR, because it's clearer about your work. Would you?

**Comment by devanshj** [comment]
> Technically, `setState` can be mutated to break compiling?

No not if the middleware author writes correct types (just like we write correct types for `devtools` and `immer`).

> I missed this part. We can suggest using devtools at leaf level.

Yes but the other way round (as I wrote "`myMiddleware(devtools(...` instead of `devtools(myMiddleware(...`" so former is problematic).

> But, probably more I read, more I get how it works, and "wow, it's good".

Ha thanks!

> From the lib maintaining perspective, adding feature (including strict checks) is easier than removing it. So, I will keep https://github.com/pmndrs/zustand/commit/fb624ac4042f5cb84de4440128bcf7cebafeab03 commit in this PR. Alternatively, as having an option is good, I will open a new PR for adding "strict replace" and I will consider merging after releasing v4 and getting more feedback. Or, maybe you want to open the PR, because it's clearer about your work. Would you?

No you got it backwards. Adding a strict check is a breaking change, so it's easier to remove it than to add it. So if you publish v4 without strict replace then you can only add it in v5 as it's a breaking change. But if you publish v4 with strict replace then you can remove it in v4.x because it won't be a breaking change. Again, idm anything just correcting you.

And sure I can open a PR if you wish.

**Comment by dai-shi** [comment]
> Yes but the other way round

oops, "at the top level", i see.

> And sure I can open a PR if you wish.

Yes, please. I will (re-)consider about it after releasing v4-rc.0 with this PR before releasing final v4.

**Comment by devanshj** [comment]
LGTM

**Comment by dai-shi** [comment]
<details>
<summary>diff -urw dist-76eeacb/esm dist-9d6e7e2/esm</summary>

```diff
diff -urw dist-76eeacb/esm/index.js dist-9d6e7e2/esm/index.js
--- dist-76eeacb/esm/index.js	2022-04-18 08:56:01.000000000 +0900
+++ dist-9d6e7e2/esm/index.js	2022-04-18 08:57:05.000000000 +0900
@@ -8,11 +8,13 @@
   useDebugValue(slice);
   return slice;
 }
-function create(createState) {
+const createImpl = (createState) => {
   const api = typeof createState === "function" ? createStore__default(createState) : createState;
   const useBoundStore = (selector, equalityFn) => useStore(api, selector, equalityFn);
   Object.assign(useBoundStore, api);
   return useBoundStore;
-}
+};
+const create = (createState) => createState ? createImpl(createState) : createImpl;
+var create$1 = create;
 
-export { create as default, useStore };
+export { create$1 as default, useStore };
diff -urw dist-76eeacb/esm/middleware.js dist-9d6e7e2/esm/middleware.js
--- dist-76eeacb/esm/middleware.js	2022-04-18 08:55:57.000000000 +0900
+++ dist-9d6e7e2/esm/middleware.js	2022-04-18 08:57:01.000000000 +0900
@@ -1,3 +1,5 @@
+import { produce } from 'immer';
+
 var __defProp$1 = Object.defineProperty;
 var __getOwnPropSymbols$1 = Object.getOwnPropertySymbols;
 var __hasOwnProp$1 = Object.prototype.hasOwnProperty;
@@ -14,7 +16,7 @@
     }
   return a;
 };
-const redux = (reducer, initial) => (set, get, api) => {
+const reduxImpl = (reducer, initial) => (set, get, api) => {
   api.dispatch = (action) => {
     set((state) => reducer(state, action), false, action);
     return action;
@@ -22,9 +24,9 @@
   api.dispatchFromDevtools = true;
   return __spreadValues$1({ dispatch: (...a) => api.dispatch(...a) }, initial);
 };
+const redux = reduxImpl;
 
-function devtools(fn, options) {
-  return (set, get, api) => {
+const devtoolsImpl = (fn, options) => (set, get, api) => {
     const devtoolsOptions = options === void 0 ? {} : typeof options === "string" ? { name: options } : options;
     let extensionConnector;
     try {
@@ -40,10 +42,11 @@
     const extension = extensionConnector.connect(devtoolsOptions);
     let isRecording = true;
     api.setState = (state, replace, nameOrAction) => {
-      set(state, replace);
+    const r = set(state, replace);
       if (!isRecording)
-        return;
+      return r;
       extension.send(nameOrAction === void 0 ? { type: devtoolsOptions.anonymousActionType || "anonymous" } : typeof nameOrAction === "string" ? { type: nameOrAction } : nameOrAction, get());
+    return r;
     };
     const setStateFromDevtools = (...a) => {
       const originalIsRecording = isRecording;
@@ -117,7 +120,7 @@
     });
     return initialState;
   };
-}
+const devtools = devtoolsImpl;
 const parseJsonThen = (stringified, f) => {
   let parsed;
   try {
@@ -129,7 +132,7 @@
     f(parsed);
 };
 
-const subscribeWithSelector = (fn) => (set, get, api) => {
+const subscribeWithSelectorImpl = (fn) => (set, get, api) => {
   const origSubscribe = api.subscribe;
   api.subscribe = (selector, optListener, options) => {
     let listener = selector;
@@ -152,8 +155,9 @@
   const initialState = fn(set, get, api);
   return initialState;
 };
+const subscribeWithSelector = subscribeWithSelectorImpl;
 
-const combine = (initialState, create) => (set, get, api) => Object.assign({}, initialState, create(set, get, api));
+const combine = (initialState, create) => (...a) => Object.assign({}, initialState, create(...a));
 
 var __defProp = Object.defineProperty;
 var __getOwnPropSymbols = Object.getOwnPropertySymbols;
@@ -196,7 +200,7 @@
     };
   }
 };
-const persist = (config, baseOptions) => (set, get, api) => {
+const persistImpl = (config, baseOptions) => (set, get, api) => {
   let options = __spreadValues({
     getStorage: () => localStorage,
     serialize: JSON.stringify,
@@ -304,5 +308,15 @@
   hydrate();
   return stateFromStorage || configResult;
 };
+const persist = persistImpl;
+
+const immerImpl = (initializer) => (set, get, store) => {
+  store.setState = (updater, replace, ...a) => {
+    const nextState = typeof updater === "function" ? produce(updater) : updater;
+    return set(nextState, replace, ...a);
+  };
+  return initializer(store.setState, get, store);
+};
+const immer = immerImpl;
 
-export { combine, devtools, persist, redux, subscribeWithSelector };
+export { combine, devtools, immer, persist, redux, subscribeWithSelector };
diff -urw dist-76eeacb/esm/vanilla.js dist-9d6e7e2/esm/vanilla.js
--- dist-76eeacb/esm/vanilla.js	2022-04-18 08:55:56.000000000 +0900
+++ dist-9d6e7e2/esm/vanilla.js	2022-04-18 08:57:00.000000000 +0900
@@ -1,4 +1,4 @@
-function createStore(createState) {
+const createStoreImpl = (createState) => {
   let state;
   const listeners = /* @__PURE__ */ new Set();
   const setState = (partial, replace) => {
@@ -18,6 +18,7 @@
   const api = { setState, getState, subscribe, destroy };
   state = createState(setState, getState, api);
   return api;
-}
+};
+const createStore = (createState) => createState ? createStoreImpl(createState) : createStoreImpl;
 
 export { createStore as default };
```

</details>

JS change seems minimal, but realized that `zustand/middleware` shouldn't depend on `immer`. I will create a follow-up PR to separate it.

**Review by dai-shi — APPROVED** [review]
Let's merge this in. Thanks so much for your work!

**Comment by devanshj** [comment]
You're welcome, and thanks for the opportunity and your patience!

**Comment by Tsimopak** [comment]
@devanshj Came across this PR from zustand's advanced typescript guide and I had to praise you for this work! it amazes me that it was made without AI, I learned a lot from it thanks <3

**Comment by devanshj** [comment]
@Tsimopak Thank you for the praise! Yes it was in pre-AI era but even now I don't think AI could come up with something like this haha... Glad you found it to be a learning resource!
